/*
INSERT INTO TB_FR_USER_ROLE_MAP
()
VALUES ( );
*/
INSERT INTO TB_FR_USER_ROLE_MAP
(ROLE_SQ ,USER_SQ ,DESCRIPTION ,CREATE_DT ,CREATE_USR_ID ,UPDATE_DT ,UPDATE_USR_ID )
VALUES
('ADM_000002', 'USR_000001', 'DESC', NOW(), 'superadmin', NOW(), 'superadmin');


INSERT INTO TB_FR_USER_ROLE_MAP
(ROLE_SQ ,USER_SQ ,DESCRIPTION ,CREATE_DT ,CREATE_USR_ID ,UPDATE_DT ,UPDATE_USR_ID )
VALUES
('ADM_000003', 'USR_000002', 'DESC', NOW(), 'superadmin', NOW(), 'superadmin');

