
INSERT INTO TB_FR_CODE_MULTI_LANG_INFO
( CODE_SQ, COUNTRY_CD, MESSAGE_VALUE,  CREATE_DT, CREATE_USR_ID )
VALUES ('CDT_000001','EN', 'CODE',   NOW(),'superadmin' );

INSERT INTO TB_FR_CODE_MULTI_LANG_INFO
( CODE_SQ, COUNTRY_CD, MESSAGE_VALUE,  CREATE_DT, CREATE_USR_ID )
VALUES ('CDT_000012','EN','LEVEL_CODE',  NOW(),'superadmin' );

INSERT INTO TB_FR_CODE_MULTI_LANG_INFO
( CODE_SQ, COUNTRY_CD, MESSAGE_VALUE,  CREATE_DT, CREATE_USR_ID )
VALUES ('GRD_000000', 'EN','L0',  NOW(),'superadmin' );

INSERT INTO TB_FR_CODE_MULTI_LANG_INFO
( CODE_SQ, COUNTRY_CD, MESSAGE_VALUE,  CREATE_DT, CREATE_USR_ID )
VALUES ('GRD_000001','EN','L1(Assistant Engineer)',  NOW(),'superadmin' );

INSERT INTO TB_FR_CODE_MULTI_LANG_INFO
( CODE_SQ, COUNTRY_CD, MESSAGE_VALUE,  CREATE_DT, CREATE_USR_ID )
VALUES ('GRD_000002','EN','L2(Assistant Engineer)',   NOW(),'superadmin' );

INSERT INTO TB_FR_CODE_MULTI_LANG_INFO
( CODE_SQ, COUNTRY_CD, MESSAGE_VALUE,  CREATE_DT, CREATE_USR_ID )
VALUES ('GRD_000003','EN','L3(Senior Engineer)',  NOW(),'superadmin' );

INSERT INTO TB_FR_CODE_MULTI_LANG_INFO
( CODE_SQ, COUNTRY_CD, MESSAGE_VALUE,  CREATE_DT, CREATE_USR_ID )
VALUES ('GRD_000004','EN','L4(Senior Engineer)',  NOW(),'superadmin' );

INSERT INTO TB_FR_CODE_MULTI_LANG_INFO
( CODE_SQ, COUNTRY_CD, MESSAGE_VALUE,  CREATE_DT, CREATE_USR_ID )
VALUES ('GRD_000005','EN','L5(Principal Engineer)',  NOW(),'superadmin' );

INSERT INTO TB_FR_CODE_MULTI_LANG_INFO
( CODE_SQ, COUNTRY_CD, MESSAGE_VALUE,  CREATE_DT, CREATE_USR_ID )
VALUES ('CDT_000013','EN','STATUS_CODE',    NOW(),'superadmin' );

INSERT INTO TB_FR_CODE_MULTI_LANG_INFO
( CODE_SQ, COUNTRY_CD, MESSAGE_VALUE,  CREATE_DT, CREATE_USR_ID )
VALUES ('USR_000001','EN','LOGIN_TYPE',   NOW(),'superadmin' );

INSERT INTO TB_FR_CODE_MULTI_LANG_INFO
( CODE_SQ, COUNTRY_CD, MESSAGE_VALUE,  CREATE_DT, CREATE_USR_ID )
VALUES ('LOG_000001','EN', 'LOG_CODE',   NOW(),'superadmin' );


INSERT INTO TB_FR_CODE_MULTI_LANG_INFO
( CODE_SQ, COUNTRY_CD, MESSAGE_VALUE,  CREATE_DT, CREATE_USR_ID )
VALUES ('STS_010000','EN','USER_STATUS',   NOW(),'superadmin' );

INSERT INTO TB_FR_CODE_MULTI_LANG_INFO
( CODE_SQ, COUNTRY_CD, MESSAGE_VALUE,  CREATE_DT, CREATE_USR_ID )
VALUES ('STS_010100','EN','On usable',  NOW(),'superadmin' );

INSERT INTO TB_FR_CODE_MULTI_LANG_INFO
( CODE_SQ, COUNTRY_CD, MESSAGE_VALUE,  CREATE_DT, CREATE_USR_ID )
VALUES ('STS_010200','EN','On waiting',  NOW(),'superadmin' );

INSERT INTO TB_FR_CODE_MULTI_LANG_INFO
( CODE_SQ, COUNTRY_CD, MESSAGE_VALUE,  CREATE_DT, CREATE_USR_ID )
VALUES ('CDT_000014','EN','MESSAGE_CODE',  NOW(),'superadmin' );

INSERT INTO TB_FR_CODE_MULTI_LANG_INFO
( CODE_SQ, COUNTRY_CD, MESSAGE_VALUE,  CREATE_DT, CREATE_USR_ID )
VALUES ('MSG_010000','EN','MESSAGE_LARGE_CATEGORY',    NOW(),'superadmin' );

INSERT INTO TB_FR_CODE_MULTI_LANG_INFO
( CODE_SQ, COUNTRY_CD, MESSAGE_VALUE,  CREATE_DT, CREATE_USR_ID )
VALUES ('MSG_010001','EN','UI', NOW(),'superadmin' );

INSERT INTO TB_FR_CODE_MULTI_LANG_INFO
( CODE_SQ, COUNTRY_CD, MESSAGE_VALUE,  CREATE_DT, CREATE_USR_ID )
VALUES ('MSG_010002','EN','COM',    NOW(),'superadmin' );

INSERT INTO TB_FR_CODE_MULTI_LANG_INFO
( CODE_SQ, COUNTRY_CD, MESSAGE_VALUE,  CREATE_DT, CREATE_USR_ID )
VALUES ('MSG_010003','EN','SERV',    NOW(),'superadmin' );

INSERT INTO TB_FR_CODE_MULTI_LANG_INFO
( CODE_SQ, COUNTRY_CD, MESSAGE_VALUE,  CREATE_DT, CREATE_USR_ID )
VALUES ('MSG_020000','EN','MESSAGE_MEDIUM_CATEGORY',   NOW(),'superadmin' );

INSERT INTO TB_FR_CODE_MULTI_LANG_INFO
( CODE_SQ, COUNTRY_CD, MESSAGE_VALUE,  CREATE_DT, CREATE_USR_ID )
VALUES ('MSG_020001','EN','MSG',  NOW(),'superadmin' );

INSERT INTO TB_FR_CODE_MULTI_LANG_INFO
( CODE_SQ, COUNTRY_CD, MESSAGE_VALUE,  CREATE_DT, CREATE_USR_ID )
VALUES ('MSG_020002','EN','TEXT',  NOW(),'superadmin' );

INSERT INTO TB_FR_CODE_MULTI_LANG_INFO
( CODE_SQ, COUNTRY_CD, MESSAGE_VALUE,  CREATE_DT, CREATE_USR_ID )
VALUES ('MSG_030000','EN','MESSAGE_SMALL_CATEGORY',  NOW(),'superadmin' );

INSERT INTO TB_FR_CODE_MULTI_LANG_INFO
( CODE_SQ, COUNTRY_CD, MESSAGE_VALUE,  CREATE_DT, CREATE_USR_ID )
VALUES ('MSG_030001','EN','ERR',   NOW(),'superadmin' );

INSERT INTO TB_FR_CODE_MULTI_LANG_INFO
( CODE_SQ, COUNTRY_CD, MESSAGE_VALUE,  CREATE_DT, CREATE_USR_ID )
VALUES ('MSG_030002','EN','WARN',   NOW(),'superadmin' );

INSERT INTO TB_FR_CODE_MULTI_LANG_INFO
( CODE_SQ, COUNTRY_CD, MESSAGE_VALUE,  CREATE_DT, CREATE_USR_ID )
VALUES ('MSG_030003','EN','LABEL',    NOW(),'superadmin' );

INSERT INTO TB_FR_CODE_MULTI_LANG_INFO
( CODE_SQ, COUNTRY_CD, MESSAGE_VALUE,  CREATE_DT, CREATE_USR_ID )
VALUES ('MSG_030004','EN','CON', NOW(),'superadmin' );

INSERT INTO TB_FR_CODE_MULTI_LANG_INFO
( CODE_SQ, COUNTRY_CD, MESSAGE_VALUE,  CREATE_DT, CREATE_USR_ID )
VALUES ('MSG_030005','EN','SUCC', NOW(),'superadmin' );

INSERT INTO TB_FR_CODE_MULTI_LANG_INFO
( CODE_SQ, COUNTRY_CD, MESSAGE_VALUE,  CREATE_DT, CREATE_USR_ID )
VALUES ('MSG_030006','EN','BTN',  NOW(),'superadmin' );

INSERT INTO TB_FR_CODE_MULTI_LANG_INFO
( CODE_SQ, COUNTRY_CD, MESSAGE_VALUE,  CREATE_DT, CREATE_USR_ID )
VALUES ('MSG_030007','EN','FORM',  NOW(),'superadmin' );

INSERT INTO TB_FR_CODE_MULTI_LANG_INFO
( CODE_SQ, COUNTRY_CD, MESSAGE_VALUE,  CREATE_DT, CREATE_USR_ID )
VALUES ('USR_000011','EN','ID LOGIN',  NOW(),'superadmin' );

INSERT INTO TB_FR_CODE_MULTI_LANG_INFO
( CODE_SQ, COUNTRY_CD, MESSAGE_VALUE,  CREATE_DT, CREATE_USR_ID )
VALUES ('USR_000012','EN','SSO LOGIN',  NOW(),'superadmin' );

INSERT INTO TB_FR_CODE_MULTI_LANG_INFO
( CODE_SQ, COUNTRY_CD, MESSAGE_VALUE,  CREATE_DT, CREATE_USR_ID )
VALUES ('STS_010300','EN','On unregistered',  NOW(),'superadmin' );

INSERT INTO TB_FR_CODE_MULTI_LANG_INFO
( CODE_SQ, COUNTRY_CD, MESSAGE_VALUE,  CREATE_DT, CREATE_USR_ID )
VALUES ('STS_010400','EN','On locked',  NOW(),'superadmin' );

INSERT INTO TB_FR_CODE_MULTI_LANG_INFO
( CODE_SQ, COUNTRY_CD, MESSAGE_VALUE,  CREATE_DT, CREATE_USR_ID )
VALUES ('LOG_000011','EN','LOGIN_CODE',  NOW(),'superadmin' );

INSERT INTO TB_FR_CODE_MULTI_LANG_INFO
( CODE_SQ, COUNTRY_CD, MESSAGE_VALUE,  CREATE_DT, CREATE_USR_ID )
VALUES ('LOG_000012','EN','LOGOUT_CODE',  NOW(),'superadmin' );

INSERT INTO TB_FR_CODE_MULTI_LANG_INFO
( CODE_SQ, COUNTRY_CD, MESSAGE_VALUE,  CREATE_DT, CREATE_USR_ID )
VALUES ('LOG_000013','EN','LOGIN_FAILED_CODE',   NOW(),'superadmin' );


