--네이밍
---대분류 UI/SERV/COM
---중분류 TEXT/MSG
---소분류 FORM/LABEL/BTN CON/WARN/ERR/SUCC/INFO
--ID 대분류_중분류_소분류

/* UI-TEXT-FORM */
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','TEXT', 'FORM','UI_TEXT_FORM_NO', 'NO',   'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','TEXT', 'FORM','UI_TEXT_FORM_USABLE', '사용여부',   'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','TEXT', 'FORM','UI_TEXT_FORM_DESCRIPTION', '설명',   'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','TEXT', 'FORM','UI_TEXT_FORM_USER_ID', '사용자ID',   'superadmin', NOW() );

INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','TEXT', 'FORM','UI_TEXT_FORM_MYSINGLE_ID', 'MySingle ID',   'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','TEXT', 'FORM','UI_TEXT_FORM_USERNAME', '사용자 이름',   'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','TEXT', 'FORM','UI_TEXT_FORM_ID', 'ID',   'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','TEXT', 'FORM','UI_TEXT_FORM_NEW_USERNAME', '이름',   'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','TEXT', 'FORM','UI_TEXT_FORM_PASSWORD', '비밀번호',   'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','TEXT', 'FORM','UI_TEXT_FORM_PASSWORD_CONFIRM', '비밀번호 확인',   'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','TEXT', 'FORM','UI_TEXT_FORM_CHANGE_PASSWORD', '변경 비밀번호',   'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','TEXT', 'FORM','UI_TEXT_FORM_CHANGE_PASSWORD_CONFIRM', '변경 비밀번호 확인',   'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','TEXT', 'FORM','UI_TEXT_FORM_WORK', '업무',   'superadmin', NOW() );

INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','TEXT', 'FORM','UI_TEXT_FORM_USERSTATUS', '사용자 상태',   'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','TEXT', 'FORM','UI_TEXT_FORM_GRD', '직급',   'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','TEXT', 'FORM','UI_TEXT_FORM_DEPT', '부서',   'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','TEXT', 'FORM','UI_TEXT_FORM_DEPT_NM', '부서명',   'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','TEXT', 'FORM','UI_TEXT_FORM_AGE', '나이',   'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','TEXT', 'FORM','UI_TEXT_FORM_BIRTH', '생년월일',   'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','TEXT', 'FORM','UI_TEXT_FORM_JOINYMD', '가입일',   'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'TEXT', 'FORM', 'UI_TEXT_FORM_ROLE_ID', '역할ID',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'TEXT', 'FORM', 'UI_TEXT_FORM_ROLE_NM', '역할명',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'TEXT', 'FORM', 'UI_TEXT_FORM_MENU_NM', '메뉴명',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'TEXT', 'FORM', 'UI_TEXT_FORM_MENU_LEVEL', '메뉴 레벨',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'TEXT', 'FORM', 'UI_TEXT_FORM_MENU_ORDER', '정렬 순서',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'TEXT', 'FORM', 'UI_TEXT_FORM_MENU_ID', '메뉴ID',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'TEXT', 'FORM', 'UI_TEXT_FORM_EMAIL', '이메일',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'TEXT', 'FORM', 'UI_TEXT_FORM_PHONENUM', '휴대전화번호',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'TEXT', 'FORM', 'UI_TEXT_FORM_WORKGROUP_ID', '업무그룹ID',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'TEXT', 'FORM', 'UI_TEXT_FORM_WORKGROUP_NM', '업무그룹명',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'TEXT', 'FORM', 'UI_TEXT_FORM_STATUS', '상태',  'superadmin', NOW() );

INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','TEXT', 'FORM','UI_TEXT_FORM_CODE_ID', '코드 ID',   'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','TEXT', 'FORM','UI_TEXT_FORM_CODE_NM', '코드명',   'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','TEXT', 'FORM','UI_TEXT_FORM_CODE_LEVEL', '코드 레벨', 'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','TEXT', 'FORM','UI_TEXT_FORM_CODE_ORDER', '정렬 순서', 'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'TEXT', 'FORM', 'UI_TEXT_FORM_ROLE', '역할',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'TEXT', 'FORM', 'UI_TEXT_FORM_TYPE', '유형',  'superadmin', NOW() );

INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'TEXT', 'FORM', 'UI_TEXT_FORM_URL', 'URL',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'TEXT', 'FORM', 'UI_TEXT_BTN_MENU_PAGE_SAVE', '메뉴 페이지 저장',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'TEXT', 'FORM', 'UI_TEXT_FORM_MENU', '메뉴',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'TEXT', 'FORM', 'UI_TEXT_FORM_READ', '읽기',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'TEXT', 'FORM', 'UI_TEXT_FORM_UPDATE', '수정',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'TEXT', 'FORM', 'UI_TEXT_FORM_EXECUTE', '실행',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'TEXT', 'FORM', 'UI_TEXT_FORM_WORKGROUP', '업무그룹',  'superadmin', NOW() );

INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'TEXT', 'FORM', 'UI_TEXT_FORM_SENDER', '발신자',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'TEXT', 'FORM', 'UI_TEXT_FORM_RECEIVER', '수신자',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'TEXT', 'FORM', 'UI_TEXT_FORM_MAILTITLE', '제목',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'TEXT', 'FORM', 'UI_TEXT_FORM_MAILCONTENT', '내용',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'TEXT', 'FORM', 'UI_TEXT_FORM_ATTACHMENT', '첨부파일',  'superadmin', NOW() );

/* UI-TEXT-LABEL */
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','TEXT', 'LABEL','UI_TEXT_LABEL_ADD_USER', '사용자 추가',   'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','TEXT', 'LABEL','UI_TEXT_LABEL_SIGNIN_USER', '회원가입',   'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','TEXT', 'LABEL','UI_TEXT_LABEL_EDIT_USER', '사용자 수정',   'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','TEXT', 'LABEL','UI_TEXT_LABEL_EDIT_MYINFO', '본인정보 수정',   'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','TEXT', 'LABEL','UI_TEXT_LABEL_DEL_USER', '사용자관리',   'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','TEXT', 'LABEL','UI_TEXT_LABEL_DEL_ROLE', '역할 삭제',   'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','TEXT', 'LABEL','UI_TEXT_BTN_SAVE', '저장',   'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'TEXT', 'LABEL', 'UI_TEXT_LABEL_MENU_TREE', '메뉴 리스트',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'TEXT', 'LABEL', 'UI_TEXT_LABEL_MENU_INFO', '메뉴 상세정보',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'TEXT', 'LABEL', 'UI_TEXT_LABEL_MENU_SEARCH', '메뉴 검색',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'TEXT', 'LABEL', 'UI_TEXT_LABEL_USER_SEARCH', '사용자 검색',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'TEXT', 'LABEL', 'UI_TEXT_LABEL_WORKGROUP_SEARCH', '업무그룹 검색',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'TEXT', 'LABEL', 'UI_TEXT_LABEL_WORKGROUP_MENU', '업무그룹별 메뉴 관리',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'TEXT', 'LABEL', 'UI_TEXT_LABEL_WORKGROUP_USER', '업무그룹별 사용자 관리',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'TEXT', 'LABEL', 'UI_TEXT_LABEL_WORKGROUP_ROLE', '업무그룹별 역할관리',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'TEXT', 'LABEL', 'UI_TEXT_LABEL_ADD_ROLE', '역할 추가',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'TEXT', 'LABEL', 'UI_TEXT_LABEL_EDIT_ROLE', '역할 수정',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'TEXT', 'LABEL', 'UI_TEXT_LABEL_EDIT_MENU', '메뉴 수정',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'TEXT', 'LABEL', 'UI_TEXT_LABEL_ADD', '추가',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'TEXT', 'LABEL', 'UI_TEXT_LABEL_ROLE_USER_MGN', '역할별 사용자 관리',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'TEXT', 'LABEL', 'UI_TEXT_LABEL_ROLE_MGN', '역할 관리',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'TEXT', 'LABEL', 'UI_TEXT_LABEL_WORKGROUP_MGN', '업무그룹 관리',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'TEXT', 'LABEL', 'UI_TEXT_LABEL_LOG_MGN', '접속이력 관리',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'TEXT', 'LABEL', 'UI_TEXT_LABEL_WORK_LOG_MGN', '작업이력 관리',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'TEXT', 'LABEL', 'UI_TEXT_LABEL_ETC_MGN', '기타 관리',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'TEXT', 'LABEL', 'UI_TEXT_LABEL_CODE_MGN', '코드 관리',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'TEXT', 'LABEL', 'UI_TEXT_LABEL_MGN_FUNC', '관리 기능',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'TEXT', 'LABEL', 'UI_TEXT_LABEL_ROLE_WORKGROUP_MGN', '역할별 업무그룹 관리',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)

VALUES ('UI', 'TEXT', 'LABEL', 'UI_TEXT_LABEL_MESSAGE_MGN', '메시지 관리',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'TEXT', 'LABEL', 'UI_TEXT_FORM_MESSAGE_KEY', 'Key',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'TEXT', 'LABEL', 'UI_TEXT_FORM_MESSAGE_VALUE', 'Value',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'TEXT', 'LABEL', 'UI_TEXT_FORM_MESSAGE_LARGE_CATEGORY', '대분류',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'TEXT', 'LABEL', 'UI_TEXT_FORM_MESSAGE_MEDIUM_CATEGORY', '중분류',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'TEXT', 'LABEL', 'UI_TEXT_FORM_MESSAGE_SMALL_CATEGORY', '소분류',  'superadmin', NOW() );

INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'TEXT', 'LABEL', 'UI_TEXT_FORM_LOG_SQ', '로그 일련번호',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'TEXT', 'LABEL', 'UI_TEXT_FORM_EVENT_IP', 'IP 주소',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'TEXT', 'LABEL', 'UI_TEXT_FORM_EVENT_DT', '로그 발생시각',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'TEXT', 'LABEL', 'UI_TEXT_FORM_EVENT_NO', '이벤트',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'TEXT', 'LABEL', 'UI_TEXT_FORM_LOG_MSG', '로그 메시지',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'TEXT', 'LABEL', 'UI_TEXT_FORM_LOGIN_SUCC', '로그인',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'TEXT', 'LABEL', 'UI_TEXT_FORM_LOGOUT', '로그아웃',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'TEXT', 'LABEL', 'UI_TEXT_FORM_LOGIN_FAIL', '로그인 실패',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'TEXT', 'LABEL', 'UI_TEXT_LABEL_MENU_PAGE_LIST', '메뉴 페이지 리스트',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'TEXT', 'LABEL', 'UI_TEXT_LABEL_MENU_AUTH_MGN', '메뉴/권한 관리',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','TEXT', 'LABEL','UI_TEXT_LABEL_ROLE_DEL', '역할 삭제',   'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','TEXT', 'LABEL','UI_TEXT_LABEL_WORKGROUP_DEL', '업무그룹 삭제',   'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','TEXT', 'LABEL','UI_TEXT_LABEL_WORKGROUP_EDIT', '업무그룹 수정',   'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','TEXT', 'LABEL','UI_TEXT_LABEL_MENU_DEL', '메뉴 삭제',   'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','TEXT', 'LABEL','UI_TEXT_LABEL_MENU_SAVE', '메뉴 저장',   'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','TEXT', 'LABEL','UI_TEXT_LABEL_DEL', '삭제',   'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'TEXT', 'LABEL', 'UI_TEXT_FORM_CREATE_USR_ID', '작성자',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'TEXT', 'LABEL', 'UI_TEXT_FORM_CREATE_DT', '작성일',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'TEXT', 'LABEL', 'UI_TEXT_FORM_UPDATE_USR_ID', '수정자',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'TEXT', 'LABEL', 'UI_TEXT_FORM_UPDATE_DT', '수정일',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'TEXT', 'LABEL', 'UI_TEXT_LABEL_CODE_TREE', '코드 리스트',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'TEXT', 'LABEL', 'UI_TEXT_LABEL_CODE_INFO', '코드 상세정보',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'TEXT', 'LABEL', 'UI_TEXT_LABEL_ADD_MENU', '메뉴 추가',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'TEXT', 'LABEL', 'UI_TEXT_LABEL_WORKGROUP_ADD', '업무그룹 추가',  'superadmin', NOW() );

INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'TEXT', 'LABEL', 'UI_TEXT_LABEL_ADD_MESSAGE', '메시지 추가',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'TEXT', 'LABEL', 'UI_TEXT_LABEL_EDIT_MESSAGE', '메시지 수정',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'TEXT', 'LABEL', 'UI_TEXT_LABEL_SEND_MAIL', '메일 전송',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'TEXT', 'LABEL', 'UI_TEXT_LABEL_SEND_MAIL_SUCCESS', '메일 전송 완료',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'TEXT', 'LABEL', 'UI_TEXT_LABEL_SEND_MAIL_FAIL', '메일 전송 실패',  'superadmin', NOW() );


/* UI-TEXT-BTN */
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','TEXT', 'BTN','UI_TEXT_BTN_ROLE_NAME', '권한 이름',   'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','TEXT', 'BTN','UI_TEXT_BTN_ADD', '추가',   'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','TEXT', 'BTN','UI_TEXT_BTN_EDIT', '수정',   'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','TEXT', 'BTN','UI_TEXT_BTN_DEL', '삭제',   'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','TEXT', 'BTN','UI_TEXT_BTN_NEW', '신규',   'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','TEXT', 'BTN','UI_TEXT_BTN_SEARCH', '조회',   'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','TEXT', 'BTN','UI_TEXT_BTN_CONFIRM', '승인',   'superadmin', NOW() );

INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','TEXT', 'BTN','UI_TEXT_BTN_CODE_SAVE', '코드정보저장',   'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','TEXT', 'BTN','UI_TEXT_BTN_USER', '사용자',   'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','TEXT', 'BTN','UI_TEXT_BTN_MENU', '메뉴',   'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','TEXT', 'BTN','UI_TEXT_BTN_ROLE', '역할',   'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','TEXT', 'BTN','UI_TEXT_BTN_EXPANDALL', '전체 펴기',   'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','TEXT', 'BTN','UI_TEXT_BTN_COLLAPSEALL', '전체 접기',   'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'TEXT', 'BTN', 'UI_TEXT_BTN_MENU_INFO_SAVE', '메뉴정보저장',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','TEXT', 'BTN','UI_TEXT_BTN_SELECT', '선택',   'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','TEXT', 'BTN','UI_TEXT_BTN_CLOSE', '닫기',   'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','TEXT', 'BTN','UI_TEXT_BTN_LIST', '목록',   'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'TEXT', 'FORM', 'UI_TEXT_BTN_SENDMAIL', '메일전송',  'superadmin', NOW() );

INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'TEXT', 'FORM', 'UI_TEXT_DOWNLOAD_FORMAT', '양식다운로드',  'superadmin',  NOW()  );
/* UI-TEXT-CON */
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','TEXT', 'ERR','UI_TEXT_CON_SAVE_COOKIE', '아이디를 저장하시겠습니까?',   'superadmin', NOW() );

/* UI-TEXT-WARN */

INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','TEXT', 'ERR','UI_TEXT_WARN_CURUSER_DELETE', '본인은 삭제가 불가능합니다.',   'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','TEXT', 'ERR','UI_TEXT_WARN_CONFIRM_USER', '사용자 승인에 실패하였습니다.',   'superadmin', NOW() );


/* UI-TEXT-ERR */
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','TEXT', 'ERR','SERV_TEXT_ERR_LOGIN', '아이디 혹은 패스워드가 틀렸습니다.',   'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','TEXT', 'ERR','SERV_TEXT_ERR_ACCOUNT_LOCK', '5회 이상 비밀번호 오류로 계정이 잠겼습니다.',   'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','TEXT', 'ERR','SERV_TEXT_ERR_ACCOUNT_ON_WAITING', '시스템 승인 대기중입니다.',   'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','TEXT', 'ERR','SERV_TEXT_ERR_ACCOUNT_NO_ROLE', '사용가능한 권한이 없습니다.',   'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','TEXT', 'ERR','SERV_TEXT_ERR_LOGIN_WITHDRAW', '탈퇴한 사용자입니다.',   'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','TEXT', 'ERR','SERV_TEXT_ERR_LOCKED_USER', '계정이 잠긴 사용자입니다.',   'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','TEXT', 'ERR','SERV_TEXT_ERR_LOGIN_DUP', '동일 계정의 아이디로 중복된 로그인이 발생하여 해당 브라우저에서 로그아웃됩니다.',   'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','TEXT', 'ERR','UI_TEXT_ERR_BOTH_PERIOD', '기간 검색의 경우, 시작 일자와 종료 일자를 모두 입력하셔야 합니다.',   'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','TEXT', 'ERR','UI_TEXT_ERR_START_EARLY', '시작 일자는 종료 일자와 같거나 빨라야 합니다.',   'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','TEXT', 'ERR','UI_TEXT_ERR_NOW_EARLY', '시작 일자, 종료 일자는 현재 일자와 같거나 빨라야 합니다.',   'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','TEXT', 'ERR','UI_TEXT_ERR_NOT_EXIST_USER', '발신자가 존재하지 않는 사용자입니다.',   'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','TEXT', 'ERR','UI_TEXT_ERR_WRONG_IP_ADDRESS', '본 시스템에서는 메일 발송을 할 수 없습니다.&lt;br&gt; 관리자에게 문의바랍니다.',   'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','TEXT', 'ERR','UI_TEXT_ERR_ESB', '메일 발송중 에러가 발생하였습니다.',   'superadmin', NOW() );


/* UI-TEXT-SUCC */

/* UI-TEXT-INFO */

/* UI-MSG-FORM */
/* UI-MSG-LABEL */
/* UI-MSG-BTN */
/* UI-MSG-CON */
/* UI-MSG-WARN */
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','MSG', 'WARN','UI_MSG_WARN_NO_SELECT_MENU', '메뉴 리스트에서 메뉴를  먼저 선택해주세요.',   'superadmin', NOW() );

INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'MSG', 'WARN', 'UI_MSG_WARN_MENUMGN_NO_ADD_MORE_TWO', '메뉴는 한번에 하나만 등록 가능합니다.',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'MSG', 'CON', 'UI_MSG_CON_MENUMGN_NO_SAVED_MENU', '저장되지 않은 신규 메뉴는 삭제됩니다. 진행하시겠습니까?',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'MSG', 'WARN', 'UI_MSG_WARN_MENUMGN_NO_SELECTED_MENU_ADD', '추가할 메뉴의 상위 메뉴를 선택해주세요',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'MSG', 'WARN', 'UI_MSG_WARN_MENUMGN_NO_SELECTED_MENU_DELETE', '삭제할 메뉴를 선택해주세요',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'MSG', 'WARN', 'UI_MSG_WARN_WRONG_URL', '[ {0} ] URL 형식이 잘못되었습니다.',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'MSG', 'WARN', 'UI_MSG_WARN_WRONG_KOENGNULLNUMCHECK', '[ {0} ] 는   _ (언더바)  .(마침표) ,(쉼표) -(하이픈) /(슬래쉬) () (괄호) 와  한글, 영어, 숫자만 입력가능합니다.',  'superadmin', NOW() );

INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'MSG', 'WARN', 'UI_MSG_WARN_ENGNUMSPCCHARCHECK', ' 는   _ (언더바)  .(마침표) ,(쉼표) -(하이픈) /(슬래쉬) () (괄호)  와  영어, 숫자만 입력가능합니다.',  'superadmin', NOW() );


INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'MSG', 'WARN', 'UI_MSG_WARN_CORRECTKOENGNULLNUMCHECK', '는  _ (언더바)  .(마침표) ,(쉼표) -(하이픈) /(슬래쉬) () (괄호) 와  정확한 한글, 영어, 숫자만 입력가능합니다.',  'superadmin', NOW() );

INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'MSG', 'WARN', 'UI_MSG_WARN_CODEMGN_NO_SAVED_CODE', '해당 코드부터 저장해 주세요.',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'MSG', 'WARN', 'UI_MSG_WARN_CODEMGN_NO_ADD_MORE_TWO', '코드는 한번에 하나만 등록 가능합니다.',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'MSG', 'WARN', 'UI_MSG_WARN_CODEMGN_NO_SAVED_MOVE_CODE', '해당 코드를 저장 후 이동해주세요.',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'MSG', 'WARN', 'UI_MSG_WARN_MENUMGN_NO_SELECTED_MENU', '선택된 메뉴 정보가 없습니다.',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'MSG', 'WARN', 'UI_MSG_WARN_MENUMGN_NO_TOPMENU_DRAG', '최상위 메뉴는 이동할 수 없습니다.',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'MSG', 'WARN', 'UI_MSG_WARN_NOT_CHANGED', '변경된 데이터가 없습니다.',  'superadmin', NOW() );

INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('COM', 'MSG', 'WARN', 'COM_MSG_WARN_MENU_ORDER_LIMITS', '정렬 순서는 1 에서 20 까지 가능합니다.',  'superadmin', NOW() );


INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('SERV', 'MSG', 'WARN', 'SERV_MSG_WARN_DELETE_MENU', '해당 메뉴는 삭제된 메뉴입니다.',  'superadmin', NOW() );

INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('SERV', 'MSG', 'WARN', 'SERV_MSG_WARN_CANNOT_UPDATE', '수정할 수 없는 데이터 입니다.',  'superadmin', NOW() );



INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'MSG', 'WARN', 'UI_MSG_WARN_REQUIRED', '는 필수값입니다.',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'MSG', 'WARN', 'UI_MSG_WARN_PHONECHECK', '전화형식이 잘못되었습니다.',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'MSG', 'WARN', 'UI_MSG_WARN_KOENGNULLNUMCHECK', '는  _  과 - _ , .  ( ) / 를  포함한 한글, 영어, 숫자만 입력가능합니다.',  'superadmin', NOW() );

INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'MSG', 'WARN', 'UI_MSG_WARN_ENGNUMCHECK', '는  _ 과 - _ , .  ( ) / 를  포함한 영어, 숫자만 입력가능합니다.',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'MSG', 'WARN', 'UI_MSG_WARN_ENGCHECK', '는 _ , - _ , .  ( ) /을  포함한 영어만 입력가능합니다.',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'MSG', 'WARN', 'UI_MSG_WARN_EMAILCHECK', '이메일 형식이 잘못되었습니다.',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'MSG', 'WARN', 'UI_MSG_WARN_ONLYNUMCHECK', '는 숫자만 입력가능합니다.',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'MSG', 'WARN', 'UI_MSG_WARN_URLCHECK', 'URL 형식이 잘못되었습니다.',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'MSG', 'WARN', 'UI_MSG_WARN_SELECTCHECK', '한개 이상의 항목을 선택해 주세요.',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'MSG', 'WARN', 'UI_MSG_WARN_NOT_EXIST_ADD', '더 이상 추가할 메뉴가 없습니다..',  'superadmin', NOW() );

INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','MSG', 'WARN','UI_MSG_WARN_ADD_MENU_NO_PARENT', '상위 메뉴를 먼저 저장하셔야합니다.',   'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'MSG', 'WARN', 'UI_MSG_WARN_NO_SAVE_DATA', '저장할 데이터가 없습니다.',  'superadmin', NOW() );

INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'MSG', 'WARN', 'UI_MSG_WARN_PASSWORD_REQUIRED', '[비밀번호]는 필수값입니다.',  'superadmin', NOW() );

INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'MSG', 'WARN', 'UI_MSG_WARN_PASSWORD_NOT_EQUAL', '[비밀번호]비밀번호란과 비밀번호 확인란의 비밀번호가 같지 않습니다.',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'MSG', 'WARN', 'UI_MSG_WARN_PASSWORD_NOT_CORRECT', '[비밀번호]비밀번호가 옳지 않습니다.',  'superadmin', NOW() );


INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'MSG', 'WARN', 'UI_MSG_WARN_ROLENM_REQUIRED', '역할명을 입력해 주세요.',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'MSG', 'WARN', 'UI_MSG_WARN_IDCHECK_REQUIRED', '[ID Check] 버튼을 눌러 ID 를 확인해야 합니다.',  'superadmin', NOW() );

INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'MSG', 'WARN', 'UI_MSG_WARN_KEY_REQUIRED', '[Key Check] 버튼을 눌러 Key 를 확인해야 합니다.',  'superadmin', NOW() );

INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'MSG', 'WARN', 'UI_MSG_WARN_KEY_NOT_EXIST', '[Key] 값은 필수값입니다.',  'superadmin', NOW() );

INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'MSG', 'WARN', 'UI_MSG_WARN_ID_AVAILABLE', '사용가능한 ID 입니다.',  'superadmin', NOW() );

INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'MSG', 'WARN', 'UI_MSG_WARN_KEY_AVAILABLE', '사용가능한 Key 입니다.',  'superadmin', NOW() );

INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'MSG', 'WARN', 'UI_MSG_WARN_ID_DUPLICATED', '중복되는 ID입니다.',  'superadmin', NOW() );

INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'MSG', 'WARN', 'UI_MSG_WARN_KEY_DUPLICATED', '중복되는 Key입니다.',  'superadmin', NOW() );

INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'MSG', 'WARN', 'UI_MSG_WARN_NOT_EXIST_MENU_NM', '해당 검색어를 포함하는 메뉴가 존재하지 않습니다.',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'MSG', 'WARN', 'UI_MSG_WARN_PW_DIGITSCHECK', '비밀번호는 8 자리 이상 20 자리 이하이여야 합니다.',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'MSG', 'WARN', 'UI_MSG_WARN_PW_COMBINATION_THREE_SCHECK', '비밀번호는 영문 대/소문자, 숫자, 특수문자 중 3가지 이상의 조합으로 생성되어야 합니다.',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'MSG', 'WARN', 'UI_MSG_WARN_PW_FOUR_CONSECUTIVE_SCHECK', '비밀번호는 영문자,숫자가 4자 이상 순차적이어서는 안됩니다. ex)abcd, 1234',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'MSG', 'WARN', 'UI_MSG_WARN_PW_FOUR_CONTINUOUS_SCHECK', '비밀번호는 같은 문자가 4회 이상 반복되어서는 안됩니다.',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'MSG', 'WARN', 'UI_MSG_WARN_PW_KEYBOARD_FOUR_CONTINUOUS_SCHECK', '비밀번호는 키보드상에 연속된 문자가 4개 이상이어서는 안됩니다. ex)qwer, asdf',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'MSG', 'WARN', 'UI_MSG_WARN_USER_IMPORT_SUCCESS_01', '총 {0}건중 ',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'MSG', 'WARN', 'UI_MSG_WARN_USER_IMPORT_SUCCESS_02', '{0}건 모두 추가성공하였습니다. ',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'MSG', 'WARN', 'UI_MSG_WARN_USER_IMPORT_FAILED_01', '총 {0}건중 &lt;br&gt;&lt;br&gt;',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'MSG', 'WARN', 'UI_MSG_WARN_USER_IMPORT_FAILED_02', '{0}건 성공, ',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'MSG', 'WARN', 'UI_MSG_WARN_USER_IMPORT_FAILED_03', '{0}건 실패 하였습니다. ',  'superadmin', NOW() );

INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'MSG', 'WARN', 'UI_MSG_WARN_ONLY_SPECIFIED_FILE_POSSIBLE', '{0} 파일만 가능합니다.',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'MSG', 'WARN', 'UI_MSG_WARN_ONLY_SPECIFIED_EXT_POSSIBLE', '{0} 확장자인 파일만 업로드 할 수 있습니다.',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'MSG', 'WARN', 'UI_MSG_WARN_ONLY_SPECIFIED_EXT_DENIED', '{0} 확장자인 파일은 업로드할 수 없습니다.',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'MSG', 'WARN', 'UI_MSG_WARN_DENIED_DUPLICATED_FILE', 'File name : {0}&lt;br&gt; 중복된 파일은 넣을 수 없습니다.',  'superadmin', NOW() );

INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'MSG', 'WARN', 'UI_MSG_WARN_OVERSIZE_FILE', '파일의 용량은 {0}MB를 초과할 수 없습니다.',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'MSG', 'WARN', 'UI_MSG_WARN_OVERSIZE_TOTAL_FILES', '업로드할 파일의 총 용량은 {0}MB를 초과할 수 없습니다.',  'superadmin', NOW() );

/* UI-MSG-SUCC */
/* UI-MSG-INFO */


/* SERV-TEXT-FORM */
/* SERV-TEXT-LABEL */
/* SERV-TEXT-BTN */
/* SERV-TEXT-CON */
/* SERV-TEXT-WARN */
/* SERV-TEXT-ERR */
/* SERV-TEXT-SUCC */
/* SERV-TEXT-INFO */

/* SERV-MSG-FORM */
/* SERV-MSG-LABEL */
/* SERV-MSG-BTN */
/* SERV-MSG-CON */
/* SERV-MSG-WARN */
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('SERV', 'MSG', 'WARN', 'SERV_MSG_WARN_MENUMGN_NO_TOPMENU_UPDATE', '최상위 메뉴는 수정할 수 없습니다.',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('SERV','MSG', 'WARN','SERV_MSG_WARN_TEXT_LENGTH_LIMITS', '[ {0} ] 는 {0} 길이까지 입력가능합니다. ',   'superadmin', NOW() );
/* SERV-MSG-ERR */
/* SERV-MSG-SUCC */
/* SERV-MSG-INFO */
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('SERV','MSG', 'INFO','SERV_MSG_INFO_PASSWORD_INFO_MAIL_TITLE', '신규사용자 임시 패스워드 발송드립니다.',   'superadmin', NOW() );

INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('SERV','MSG', 'INFO','SERV_MSG_INFO_PASSWORD_INFO_MAIL_CONTENT', '님의 임시 패스워드를 발송드립니다.&lt;br&gt;&lt;br&gt;로그인 후 Password 변경 부탁드립니다. &lt;br&gt;&lt;br&gt; 현재 Password : ',   'superadmin', NOW() );


/* COM-TEXT-FORM */
/* COM-TEXT-LABEL */
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('COM', 'TEXT', 'LABEL', 'COM_TEXT_LABEL_AUTO_MENU_ID', '{0}는 자동으로 생성됩니다.',  'superadmin', NOW() );

/* COM-TEXT-BTN */
/* COM-TEXT-CON */
/* COM-TEXT-WARN */
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('COM','MSG', 'WARN','COM_MSG_WARN_MENU_LEVEL_LIMITS', '메뉴레벨은 1 부터 3 까지 입력 가능힙니다.',   'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('COM','MSG', 'WARN','COM_MSG_WARN_MENU_URL_REQUIRED', '메뉴레벨이 3 인 경우 메뉴 URL 은 필수값입니다.',   'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('COM','MSG', 'WARN','COM_MSG_WARN_1_LEVEL_MENU_LIMITS', '메뉴레벨이 1 인 경우 5 개 까지 저장 가능합니다.',   'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('COM', 'MSG', 'WARN', 'COM_MSG_WARN_MENUMGN_NO_TOPMENU_DELETE', '최상위 메뉴는 삭제할 수 없습니다.',  'superadmin', NOW() );

INSERT INTO TB_FR_MESSAGE_INFO( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','MSG', 'SUCC','UI_MSG_WARN_SUCC_MENU_DRAG_DROP_SUCC', '메뉴 위치가 변경되었습니다. 메뉴정보저장 후에 반영됩니다.',   'superadmin', NOW() );


INSERT INTO TB_FR_MESSAGE_INFO( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','MSG', 'WARN','UI_MSG_WARN_MENU_PAGE_INSERT_NO_MENUSQ', '신규 시에는 메뉴를 먼저 저장해야 메뉴페이지 추가가 가능합니다.',   'superadmin', NOW() );

INSERT INTO TB_FR_MESSAGE_INFO( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','MSG', 'WARN','UI_MSG_WARN_MENU_PAGE_INSERT_NO_MENUURL', '메뉴 URL 이 없으면  메뉴 페이지를 추가할 수 없습니다. ',   'superadmin', NOW() );

INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('COM', 'MSG', 'WARN', 'COM_MSG_WARN_MENUMGN_MENU_UPDATE_HASITEMS', '하위 메뉴가 있는 메뉴는 메뉴레벨을 변경할 수 없습니다.',  'superadmin', NOW() );



INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'MSG', 'SUCC', 'UI_MSG_SUCC_SAVED_MENU', '성공적으로 저장되었습니다. 화면 리로딩 시 저장된 메뉴가 반영됩니다.',  'superadmin', NOW() );

INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('COM', 'MSG', 'WARN', 'COM_MSG_WARN_ROLEMGN_CANNOT_DELETE_ADMIN_ROLE', '시스템 관리자 역할은 삭제할 수 없습니다.',  'superadmin', NOW() );

INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('COM', 'MSG', 'WARN', 'COM_MSG_WARN_WORKGROUP_CANNOT_DELETE_ADMIN_WORKGROUP', '시스템 관리자 업무그룹은 삭제할 수 없습니다.',  'superadmin', NOW() );


/* COM-TEXT-ERR */
/* COM-TEXT-SUCC */
/* COM-TEXT-INFO */

/* COM-MSG-FORM */
/* COM-MSG-LABEL */
/* COM-MSG-BTN */

/* COM-MSG-CON */
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'MSG', 'CON', 'UI_MSG_CON_DELETE', '정말로 삭제하시겠습니까?',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'MSG', 'CON', 'UI_MSG_CON_ROLE_SAVED_DATA', '역할에 등록된 데이터가 존재합니다.&lt;br/&gt;정말로 삭제하시겠습니까?',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'MSG', 'CON', 'UI_MSG_CON_WORKGROUP_SAVED_DATA', '업무그룹에 등록된 데이터가 존재합니다.&lt;br/&gt;정말로 삭제하시겠습니까?',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'MSG', 'CON', 'UI_MSG_CON_ADD', '선택된 리스트를 추가하시겠습니까?',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'MSG', 'CON', 'UI_MSG_CON_SAVE', '선택된 리스트를 저장하시겠습니까?',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'MSG', 'CON', 'UI_MSG_CON_USER', '선택된 사용자를 승인하시겠습니까?',  'superadmin', NOW() );

/* COM-MSG-WARN */
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('COM', 'MSG', 'WARN', 'COM_MSG_WARN_MENUMGN_MENU_DELETE_HASITEMS', '하위 메뉴가 있어 삭제할 수 없습니다.',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('COM', 'MSG', 'WARN', 'COM_MSG_WARN_CODEMGN_CODE_DELETE_HASITEMS', '하위 코드가 있어 삭제할 수 없습니다.',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('COM', 'MSG', 'WARN', 'COM_MSG_WARN_COM_REQUIRED', '[ {0} ] 는 필수값입니다.',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('COM', 'MSG', 'WARN', 'COM_MSG_WARN_COM_NOT_EXIST', '[ {0} ] 에 해당하는 값이 존재하지 않습니다.',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('COM', 'MSG', 'WARN', 'COM_MSG_WARN_COM_ALREADY_EXIST', '[ {0} ] 에 해당하는 값이 이미 존재합니다.',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('COM', 'MSG', 'WARN', 'COM_MSG_WARN_COM_WRONG_DATA', '[ {0} ] 에 잘못된 값이 입력되었습니다.',  'superadmin', NOW() );

/* COM-MSG-ERR */
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('COM','MSG', 'ERR','COM_MSG_ERR_995', '접근권한 재설정 중 에러가 발생하였습니다.',   'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('COM','MSG', 'ERR','COM_MSG_ERR_997', '접근할 수 있는 권한이 없습니다.',   'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('COM','MSG', 'ERR','COM_MSG_ERR_999', '예상 할 수 없는 에러가 발생하였습니다.',   'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('COM','MSG', 'ERR','COM_MSG_ERR_998', '조회된 데이터 결과가 존재하지 않습니다.',   'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('COM','MSG', 'ERR','COM_MSG_ERR_996', 'LOG INSERT 중 에러가 발생하였습니다.',   'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('COM','MSG', 'ERR','COM_MSG_ERR_ALREADY_DELETED', '이미 삭제되거나 없는 데이터 입니다.',   'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('COM','MSG', 'ERR','COM_MSG_ERR_USED_CODE', '사용중인 코드입니다. 삭제할 수 없습니다.',   'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('COM','MSG', 'ERR','COM_MSG_ERR_FILE_NOT_EXCEL', 'Excel 형식이 아니거나 암호화 되어있는 파일입니다.',   'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('COM','MSG', 'ERR','COM_MSG_ERR_FAIL_LOAD_EXCEL', 'Excel파일 로드중에 오류가 발생하였습니다.',   'superadmin', NOW() );

/* COM-MSG-SUCC */

/* COM-MSG-INFO */
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'MSG', 'SUCC', 'UI_MSG_SUCC_SAVE', '성공적으로 저장되었습니다.',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'MSG', 'SUCC', 'UI_MSG_SUCC_ADD', '성공적으로 추가되었습니다.',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'MSG', 'SUCC', 'UI_MSG_DEL_SAVE', '성공적으로 삭제되었습니다.',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'MSG', 'SUCC', 'UI_MSG_DEL_FAIL', '삭제할 수 없습니다.',  'superadmin', NOW() );
INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'MSG', 'SUCC', 'UI_MSG_EDIT_FAIL', '수정할 수 없습니다.',  'superadmin', NOW() );

INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'MSG', 'WARN', 'UI_MSG_WARN_NO_SELECTED_DELETE_DATA', '삭제할 데이터를 선택해주세요.',  'superadmin', NOW() );

INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('SERV', 'MSG', 'ERR', 'SERV_MSG_ERR_NO_ROLE', '해당 페이지에 권한이 없습니다.',  'superadmin', NOW() );

INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'TEXT', 'LABEL', 'UI_TEXT_LABEL_CHANGE_USER', '사용자 변경',  'superadmin', NOW() );

INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','TEXT', 'BTN','UI_TEXT_BTN_CHANGE', '변경',   'superadmin', NOW() );

INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','TEXT', 'BTN','UI_TEXT_BTN_EXIT', '종료',   'superadmin', NOW() );

INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','MSG', 'WARN','UI_MSG_WARN__NO_SIGN_MYSINGE_SSO', 'SSO 정보가 없어 로그인 페이지로 이동합니다. 계속 진행하시겠습니다?',   'superadmin', NOW() );

INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','MSG', 'WARN','UI_MSG_WARN_NO_IE_MYSINGE_SSO', '본 시스템은 Internet Explorer 11 에서만 접속가능합니다. ',   'superadmin', NOW() );

INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','MSG', 'WARN','UI_MSG_WARN_NOT_EXIST_USER_ID', '해당 사용자ID가 존재하지 않습니다. ',   'superadmin', NOW() );

INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','TEXT', 'LABEL','UI_TEXT_LABEL_USER_INFO_REG', '사용자 정보 등록',   'superadmin', NOW() );

INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','TEXT', 'FORM','UI_TEXT_FORM_REAL_USER_ID', '실사용자ID',   'superadmin', NOW() );

INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','TEXT', 'FORM','UI_TEXT_LABEL_LANGUAGE', '언어',   'superadmin', NOW() );

INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','MSG', 'CON','UI_TEXT_CON_CHANG_LANGUAGE', '정말로 언어를 변경하시겠습니까?&lt;br/&gt; 언어가 변경되면 index 페이지로 이동합니다.',   'superadmin', NOW() );


INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','MSG', 'CON','UI_TEXT_CON_CHANG_DEFAUT_LANGUAGE', '기본 언어가 변경되어  index 페이지로 이동합니다.',   'superadmin', NOW() );


INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('COM','MSG', 'WARN','COM_MSG_WARN_NOT_EXIST_CURRENT_USER_ID', '현재 사용자ID가 존재하지 않습니다.',   'superadmin', NOW() );

INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','TEXT', 'LABEL','UI_TEXT_LABEL_SAVE_ID', '아이디 저장',   'superadmin', NOW() );

INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','TEXT', 'LABEL','UI_TEXT_LABEL_JOIN_MEMBER', '회원가입',   'superadmin', NOW() );

INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','TEXT', 'LABEL','UI_TEXT_LABEL_SYSTEM_CONTACT', '시스템 문의 연락처',   'superadmin', NOW() );

INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','TEXT', 'LABEL','UI_TEXT_SYSTEM_LICENCE', '삼성SDS 임직원을 위한 시스템으로서 인가된 분만 사용 가능하며, 불법적으로 사용 시 법적 제재를 받을 수 있습니다.',   'superadmin', NOW() );

INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'TEXT', 'LABEL', 'UI_TEXT_LABEL_METHOD_NAME', '메서드명',  'superadmin', NOW() );

INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'TEXT', 'LABEL', 'UI_TEXT_LABEL_WORK_LOG_DETAIL', '작업이력 상세내역',  'superadmin', NOW() );

INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'TEXT', 'LABEL', 'UI_TEXT_LABEL_COMBO_ALL', '전체',  'superadmin', NOW() );

INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('COM','MSG', 'ERR','COM_MSG_ERR_EXPIRED_SESSION', '세션이 만료되었습니다. 로그인 페이지로 이동하시겠습니까?',   'superadmin', NOW() );

INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'TEXT', 'LABEL', 'UI_TEXT_LABEL_END_IMPERSON', '사용자변경 종료',  'superadmin', NOW() );

INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('SERV','TEXT', 'ERR','SERV_TEXT_ERR_NOT_USE_THIS_FUNC', '해당 사용자로는 이 기능을 수행할 수 없습니다.&lt;br&gt;(업무그룹-사용자나 사용자-역할을 등록해야 사용 가능합니다.)',   'superadmin', NOW() );

INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('SERV','TEXT', 'ERR','SERV_TEXT_ERR_NOT_USING_USER', '사용중인 사용자가 아닙니다.',   'superadmin', NOW() );

INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('SERV','TEXT', 'ERR','SERV_TEXT_ERR_NOT_CHANGE_CURRENT_USER', '현재와 동일한 계정으로 변경할 수 없습니다.',   'superadmin', NOW() );

INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('SERV','TEXT', 'ERR','SERV_TEXT_ERR_NOT_EXIST_CHANGED_USER', '변경될 사용자 정보가 존재하지 않습니다.',   'superadmin', NOW() );

INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('SERV','TEXT', 'ERR','SERV_TEXT_ERR_ALREADY_END_IMPERSON', '이미 사용자 변경이 종료되었습니다.<br>새로고침(F5)을 눌러주세요.',   'superadmin', NOW() );

INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI', 'TEXT', 'LABEL', 'UI_TEXT_LABEL_CHANGE_PASSWORD', '패스워드 변경',  'superadmin', NOW() );

INSERT INTO TB_FR_MESSAGE_INFO
( LARGE_CATEGORY, MEDIUM_CATEGORY, SMALL_CATEGORY, MESSAGE_KEY, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI','TEXT', 'FORM','UI_TEXT_FORM_COUNTRY_CODE', '국가번호',   'superadmin', NOW() );