INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('CDT_000001','CODE', 'CODE', '0', 'Main CODE' , '0', NOW(),'superadmin', NOW(),'superadmin', 'Y', 1);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('CBO_000001','국가코드', 'Country code', 'CDT_000001',  '국가코드' , '1', NOW(),'superadmin', NOW(),'superadmin', 'Y', 1);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('GH_000000', '가나', 'Ghana', 'CBO_000001', '가나' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 1);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('GA_000000', '가봉', 'Gabon', 'CBO_000001', '가봉' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 2);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('GY_000000', '가이아나', 'Guyana', 'CBO_000001', '가이아나' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 3);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('GM_000000', '감비아', 'Gambia', 'CBO_000001', '감비아' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 4);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('GG_000000', '건지 섬', 'Guernsey', 'CBO_000001', '건지 섬' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 5);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('GP_000000', '과들루프', 'Guadeloupe', 'CBO_000001', '과들루프' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 6);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('GT_000000', '과테말라', 'Guatemala', 'CBO_000001', '과테말라' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 7);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('GU_000000', '괌', 'Guam', 'CBO_000001', '괌' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 8);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('GD_000000', '그레나다', 'Grenada', 'CBO_000001', '그레나다' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 9);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('GR_000000', '그리스', 'Greece', 'CBO_000001', '그리스' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 10);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('GL_000000', '그린란드', 'Greenland', 'CBO_000001', '그린란드' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 11);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('GN_000000', '기니', 'Guinea', 'CBO_000001', '기니' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 12);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('GW_000000', '기니비사우', 'Guinea-Bissau', 'CBO_000001', '기니비사우' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 13);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('NA_000000', '나미비아', 'Namibia', 'CBO_000001', '나미비아' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 14);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('NR_000000', '나우루', 'Nauru', 'CBO_000001', '나우루' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 15);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('NG_000000', '나이지리아', 'Nigeria', 'CBO_000001', '나이지리아' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 16);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('AQ_000000', '남극', 'Antarctica', 'CBO_000001', '남극' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 17);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('SS_000000', '남수단', 'South Sudan', 'CBO_000001', '남수단' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 18);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('ZA_000000', '남아프리카 공화국', 'South Africa', 'CBO_000001', '남아프리카 공화국' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 19);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('NL_000000', '네덜란드', 'Netherlands', 'CBO_000001', '네덜란드' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 20);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('AN_000000', '네덜란드령 안틸레스', 'Netherlands Antilles', 'CBO_000001', '네덜란드령 안틸레스' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 21);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('NP_000000', '네팔', 'Nepal', 'CBO_000001', '네팔' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 22);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('NO_000000', '노르웨이', 'Norway', 'CBO_000001', '노르웨이' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 23);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('NF_000000', '노퍽 섬', 'Norfolk Island', 'CBO_000001', '노퍽 섬' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 24);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('NC_000000', '누벨칼레도니', 'New Caledonia', 'CBO_000001', '누벨칼레도니' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 25);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('NZ_000000', '뉴질랜드', 'New Zealand', 'CBO_000001', '뉴질랜드' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 26);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('NU_000000', '니우에', 'Niue', 'CBO_000001', '니우에' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 27);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('NE_000000', '니제르', 'Niger', 'CBO_000001', '니제르' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 28);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('NI_000000', '니카라과', 'Nicaragua', 'CBO_000001', '니카라과' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 29);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('KR_000000', '대한민국', 'Korea (Republic of)', 'CBO_000001', '대한민국' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 30);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('DK_000000', '덴마크', 'Denmark', 'CBO_000001', '덴마크' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 31);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('DM_000000', '도미니카 연방', 'Dominica', 'CBO_000001', '도미니카 연방' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 32);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('DO_000000', '도미니카 공화국', 'Dominican Republic', 'CBO_000001', '도미니카 공화국' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 33);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('DE_000000', '독일', 'Germany', 'CBO_000001', '독일' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 34);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('TL_000000', '동티모르', 'Timor-Leste', 'CBO_000001', '동티모르' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 35);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('LA_000000', '라오스', 'Lao People's Democratic Republic', 'CBO_000001', '라오스' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 36);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('LR_000000', '라이베리아', 'Liberia', 'CBO_000001', '라이베리아' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 37);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('LV_000000', '라트비아', 'Latvia', 'CBO_000001', '라트비아' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 38);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('RU_000000', '러시아', 'Russian Federation', 'CBO_000001', '러시아' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 39);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('LB_000000', '레바논', 'Lebanon', 'CBO_000001', '레바논' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 40);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('LS_000000', '레소토', 'Lesotho', 'CBO_000001', '레소토' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 41);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('RE_000000', '레위니옹', 'Réunion', 'CBO_000001', '레위니옹' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 42);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('RO_000000', '루마니아', 'Romania', 'CBO_000001', '루마니아' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 43);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('LU_000000', '룩셈부르크', 'Luxembourg', 'CBO_000001', '룩셈부르크' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 44);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('RW_000000', '르완다', 'Rwanda', 'CBO_000001', '르완다' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 45);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('LY_000000', '리비아', 'Libya', 'CBO_000001', '리비아' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 46);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('LT_000000', '리투아니아', 'Lithuania', 'CBO_000001', '리투아니아' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 47);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('LI_000000', '리히텐슈타인', 'Liechtenstein', 'CBO_000001', '리히텐슈타인' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 48);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('MG_000000', '마다가스카르', 'Madagascar', 'CBO_000001', '마다가스카르' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 49);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('MQ_000000', '마르티니크', 'Martinique', 'CBO_000001', '마르티니크' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 50);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('MH_000000', '마셜 제도', 'Marshall Islands', 'CBO_000001', '마셜 제도' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 51);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('YT_000000', '마요트', 'Mayotte', 'CBO_000001', '마요트' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 52);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('MO_000000', '마카오', 'Macao', 'CBO_000001', '마카오' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 53);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('MK_000000', '마케도니아 공화국', 'Macedonia (the former Yugoslav Republic of)', 'CBO_000001', '마케도니아 공화국' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 54);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('MW_000000', '말라위', 'Malawi', 'CBO_000001', '말라위' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 55);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('MY_000000', '말레이시아', 'Malaysia', 'CBO_000001', '말레이시아' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 56);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('ML_000000', '말리', 'Mali', 'CBO_000001', '말리' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 57);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('IM_000000', '맨 섬', 'Isle of Man', 'CBO_000001', '맨 섬' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 58);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('MX_000000', '멕시코', 'Mexico', 'CBO_000001', '멕시코' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 59);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('MC_000000', '모나코', 'Monaco', 'CBO_000001', '모나코' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 60);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('MA_000000', '모로코', 'Morocco', 'CBO_000001', '모로코' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 61);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('MU_000000', '모리셔스', 'Mauritius', 'CBO_000001', '모리셔스' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 62);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('MR_000000', '모리타니', 'Mauritania', 'CBO_000001', '모리타니' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 63);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('MZ_000000', '모잠비크', 'Mozambique', 'CBO_000001', '모잠비크' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 64);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('ME_000000', '몬테네그로', 'Montenegro', 'CBO_000001', '몬테네그로' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 65);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('MS_000000', '몬트세랫', 'Montserrat', 'CBO_000001', '몬트세랫' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 66);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('MD_000000', '몰도바', 'Moldova (Republic of)', 'CBO_000001', '몰도바' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 67);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('MV_000000', '몰디브', 'Maldives', 'CBO_000001', '몰디브' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 68);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('MT_000000', '몰타', 'Malta', 'CBO_000001', '몰타' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 69);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('MN_000000', '몽골', 'Mongolia', 'CBO_000001', '몽골' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 70);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('US_000000', '미국', 'United States of America', 'CBO_000001', '미국' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 71);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('UM_000000', '미국령 군소 제도', 'United States Minor Outlying Islands', 'CBO_000001', '미국령 군소 제도' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 72);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('VI_000000', '미국령 버진아일랜드', 'Virgin Islands (U.S.)', 'CBO_000001', '미국령 버진아일랜드' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 73);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('MM_000000', '미얀마', 'Myanmar', 'CBO_000001', '미얀마' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 74);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('FM_000000', '미크로네시아 연방', 'Micronesia (Federated States of)', 'CBO_000001', '미크로네시아 연방' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 75);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('VU_000000', '바누아투', 'Vanuatu', 'CBO_000001', '바누아투' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 76);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('BH_000000', '바레인', 'Bahrain', 'CBO_000001', '바레인' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 77);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('BB_000000', '바베이도스', 'Barbados', 'CBO_000001', '바베이도스' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 78);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('VA_000000', '바티칸 시국', 'Holy See', 'CBO_000001', '바티칸 시국' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 79);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('BS_000000', '바하마', 'Bahamas', 'CBO_000001', '바하마' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 80);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('BD_000000', '방글라데시', 'Bangladesh', 'CBO_000001', '방글라데시' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 81);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('BM_000000', '버뮤다', 'Bermuda', 'CBO_000001', '버뮤다' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 82);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('BJ_000000', '베냉', 'Benin', 'CBO_000001', '베냉' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 83);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('VE_000000', '베네수엘라', 'Venezuela (Bolivarian Republic of)', 'CBO_000001', '베네수엘라' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 84);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('VN_000000', '베트남', 'Viet Nam', 'CBO_000001', '베트남' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 85);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('BE_000000', '벨기에', 'Belgium', 'CBO_000001', '벨기에' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 86);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('BY_000000', '벨라루스', 'Belarus', 'CBO_000001', '벨라루스' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 87);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('BZ_000000', '벨리즈', 'Belize', 'CBO_000001', '벨리즈' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 88);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('BA_000000', '보스니아 헤르체고비나', 'Bosnia and Herzegovina', 'CBO_000001', '보스니아 헤르체고비나' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 89);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('BW_000000', '보츠와나', 'Botswana', 'CBO_000001', '보츠와나' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 90);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('BO_000000', '볼리비아', 'Bolivia (Plurinational State of)', 'CBO_000001', '볼리비아' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 91);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('BI_000000', '부룬디', 'Burundi', 'CBO_000001', '부룬디' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 92);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('BF_000000', '부르키나파소', 'Burkina Faso', 'CBO_000001', '부르키나파소' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 93);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('BV_000000', '부베 섬', 'Bouvet Island', 'CBO_000001', '부베 섬' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 94);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('BT_000000', '부탄', 'Bhutan', 'CBO_000001', '부탄' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 95);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('MP_000000', '북마리아나 제도', 'Northern Mariana Islands', 'CBO_000001', '북마리아나 제도' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 96);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('BG_000000', '불가리아', 'Bulgaria', 'CBO_000001', '불가리아' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 97);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('BR_000000', '브라질', 'Brazil', 'CBO_000001', '브라질' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 98);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('BN_000000', '브루나이', 'Brunei Darussalam', 'CBO_000001', '브루나이' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 99);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('WS_000000', '사모아', 'Samoa', 'CBO_000001', '사모아' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 100);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('SA_000000', '사우디아라비아', 'Saudi Arabia', 'CBO_000001', '사우디아라비아' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 101);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('GS_000000', '사우스조지아 사우스샌드위치 제도', 'South Georgia and the South Sandwich Islands', 'CBO_000001', '사우스조지아 사우스샌드위치 제도' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 102);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('SM_000000', '산마리노', 'San Marino', 'CBO_000001', '산마리노' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 103);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('ST_000000', '상투메 프린시페', 'Sao Tome and Principe', 'CBO_000001', '상투메 프린시페' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 104);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('PM_000000', '생피에르 미클롱', 'Saint Pierre and Miquelon', 'CBO_000001', '생피에르 미클롱' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 105);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('EH_000000', '서사하라', 'Western Sahara', 'CBO_000001', '서사하라' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 106);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('SN_000000', '세네갈', 'Senegal', 'CBO_000001', '세네갈' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 107);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('RS_000000', '세르비아', 'Serbia', 'CBO_000001', '세르비아' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 108);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('SC_000000', '세이셸', 'Seychelles', 'CBO_000001', '세이셸' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 109);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('LC_000000', '세인트루시아', 'Saint Lucia', 'CBO_000001', '세인트루시아' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 110);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('VC_000000', '세인트빈센트 그레나딘', 'Saint Vincent and the Grenadines', 'CBO_000001', '세인트빈센트 그레나딘' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 111);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('KN_000000', '세인트키츠 네비스', 'Saint Kitts and Nevis', 'CBO_000001', '세인트키츠 네비스' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 112);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('SH_000000', '세인트헬레나', 'Saint Helena, Ascension and Tristan da Cunha', 'CBO_000001', '세인트헬레나' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 113);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('SO_000000', '소말리아', 'Somalia', 'CBO_000001', '소말리아' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 114);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('SB_000000', '솔로몬 제도', 'Solomon Islands', 'CBO_000001', '솔로몬 제도' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 115);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('SD_000000', '수단', 'Sudan', 'CBO_000001', '수단' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 116);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('SR_000000', '수리남', 'Suriname', 'CBO_000001', '수리남' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 117);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('LK_000000', '스리랑카', 'Sri Lanka', 'CBO_000001', '스리랑카' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 118);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('SJ_000000', '스발바르 얀마옌 제도', 'Svalbard and Jan Mayen', 'CBO_000001', '스발바르 얀마옌 제도' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 119);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('SZ_000000', '스와질란드', 'Swaziland', 'CBO_000001', '스와질란드' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 120);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('SE_000000', '스웨덴', 'Sweden', 'CBO_000001', '스웨덴' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 121);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('CH_000000', '스위스', 'Switzerland', 'CBO_000001', '스위스' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 122);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('ES_000000', '스페인', 'Spain', 'CBO_000001', '스페인' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 123);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('SK_000000', '슬로바키아', 'Slovakia', 'CBO_000001', '슬로바키아' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 124);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('SI_000000', '슬로베니아', 'Slovenia', 'CBO_000001', '슬로베니아' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 125);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('SY_000000', '시리아', 'Syrian Arab Republic', 'CBO_000001', '시리아' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 126);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('SL_000000', '시에라리온', 'Sierra Leone', 'CBO_000001', '시에라리온' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 127);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('SG_000000', '싱가포르', 'Singapore', 'CBO_000001', '싱가포르' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 128);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('AE_000000', '아랍에미리트', 'United Arab Emirates', 'CBO_000001', '아랍에미리트' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 129);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('AW_000000', '아루바', 'Aruba', 'CBO_000001', '아루바' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 130);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('AM_000000', '아르메니아', 'Armenia', 'CBO_000001', '아르메니아' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 131);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('AR_000000', '아르헨티나', 'Argentina', 'CBO_000001', '아르헨티나' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 132);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('AS_000000', '아메리칸사모아', 'American Samoa', 'CBO_000001', '아메리칸사모아' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 133);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('IS_000000', '아이슬란드', 'Iceland', 'CBO_000001', '아이슬란드' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 134);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('HT_000000', '아이티', 'Haiti', 'CBO_000001', '아이티' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 135);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('IE_000000', '아일랜드', 'Ireland', 'CBO_000001', '아일랜드' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 136);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('AZ_000000', '아제르바이잔', 'Azerbaijan', 'CBO_000001', '아제르바이잔' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 137);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('AF_000000', '아프가니스탄', 'Afghanistan', 'CBO_000001', '아프가니스탄' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 138);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('AD_000000', '안도라', 'Andorra', 'CBO_000001', '안도라' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 139);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('AL_000000', '알바니아', 'Albania', 'CBO_000001', '알바니아' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 140);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('DZ_000000', '알제리', 'Algeria', 'CBO_000001', '알제리' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 141);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('AO_000000', '앙골라', 'Angola', 'CBO_000001', '앙골라' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 142);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('AG_000000', '앤티가 바부다', 'Antigua and Barbuda', 'CBO_000001', '앤티가 바부다' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 143);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('AI_000000', '앵귈라', 'Anguilla', 'CBO_000001', '앵귈라' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 144);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('ER_000000', '에리트레아', 'Eritrea', 'CBO_000001', '에리트레아' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 145);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('EE_000000', '에스토니아', 'Estonia', 'CBO_000001', '에스토니아' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 146);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('EC_000000', '에콰도르', 'Ecuador', 'CBO_000001', '에콰도르' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 147);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('ET_000000', '에티오피아', 'Ethiopia', 'CBO_000001', '에티오피아' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 148);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('SV_000000', '엘살바도르', 'El Salvador', 'CBO_000001', '엘살바도르' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 149);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('GB_000000', '영국', 'United Kingdom of Great Britain and Northern Ireland', 'CBO_000001', '영국' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 150);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('VG_000000', '영국령 버진아일랜드', 'Virgin Islands (British)', 'CBO_000001', '영국령 버진아일랜드' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 151);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('IO_000000', '영국령 인도양 지역', 'British Indian Ocean Territory', 'CBO_000001', '영국령 인도양 지역' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 152);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('YE_000000', '예멘', 'Yemen', 'CBO_000001', '예멘' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 153);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('OM_000000', '오만', 'Oman', 'CBO_000001', '오만' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 154);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('AU_000000', '오스트레일리아', 'Australia', 'CBO_000001', '오스트레일리아' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 155);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('AT_000000', '오스트리아', 'Austria', 'CBO_000001', '오스트리아' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 156);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('HN_000000', '온두라스', 'Honduras', 'CBO_000001', '온두라스' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 157);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('AX_000000', '올란드 제도', 'Åland Islands', 'CBO_000001', '올란드 제도' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 158);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('JO_000000', '요르단', 'Jordan', 'CBO_000001', '요르단' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 159);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('UG_000000', '우간다', 'Uganda', 'CBO_000001', '우간다' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 160);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('UY_000000', '우루과이', 'Uruguay', 'CBO_000001', '우루과이' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 161);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('UZ_000000', '우즈베키스탄', 'Uzbekistan', 'CBO_000001', '우즈베키스탄' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 162);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('UA_000000', '우크라이나', 'Ukraine', 'CBO_000001', '우크라이나' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 163);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('WF_000000', '왈리스 퓌튀나', 'Wallis and Futuna', 'CBO_000001', '왈리스 퓌튀나' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 164);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('IQ_000000', '이라크', 'Iraq', 'CBO_000001', '이라크' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 165);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('IR_000000', '이란', 'Iran (Islamic Republic of)', 'CBO_000001', '이란' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 166);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('IL_000000', '이스라엘', 'Israel', 'CBO_000001', '이스라엘' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 167);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('EG_000000', '이집트', 'Egypt', 'CBO_000001', '이집트' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 168);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('IT_000000', '이탈리아', 'Italy', 'CBO_000001', '이탈리아' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 169);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('ID_000000', '인도네시아', 'Indonesia', 'CBO_000001', '인도네시아' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 170);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('IN_000000', '인도', 'India', 'CBO_000001', '인도' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 171);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('JP_000000', '일본', 'Japan', 'CBO_000001', '일본' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 172);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('JM_000000', '자메이카', 'Jamaica', 'CBO_000001', '자메이카' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 173);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('ZM_000000', '잠비아', 'Zambia', 'CBO_000001', '잠비아' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 174);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('JE_000000', '저지 섬', 'Jersey', 'CBO_000001', '저지 섬' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 175);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('GQ_000000', '적도 기니', 'Equatorial Guinea', 'CBO_000001', '적도 기니' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 176);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('KP_000000', '조선민주주의인민공화국', 'Korea (Democratic People's Republic of)', 'CBO_000001', '조선민주주의인민공화국' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 177);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('GE_000000', '조지아', 'Georgia', 'CBO_000001', '조지아' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 178);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('CF_000000', '중앙아프리카 공화국', 'Central African Republic', 'CBO_000001', '중앙아프리카 공화국' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 179);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('TW_000000', '중화민국', 'Taiwan, Province of China', 'CBO_000001', '중화민국' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 180);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('CN_000000', '중화인민공화국', 'China', 'CBO_000001', '중화인민공화국' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 181);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('DJ_000000', '지부티', 'Djibouti', 'CBO_000001', '지부티' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 182);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('GI_000000', '지브롤터', 'Gibraltar', 'CBO_000001', '지브롤터' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 183);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('ZW_000000', '짐바브웨', 'Zimbabwe', 'CBO_000001', '짐바브웨' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 184);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('TD_000000', '차드', 'Chad', 'CBO_000001', '차드' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 185);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('CZ_000000', '체코', 'Czech Republic', 'CBO_000001', '체코' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 186);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('CL_000000', '칠레', 'Chile', 'CBO_000001', '칠레' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 187);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('CM_000000', '카메룬', 'Cameroon', 'CBO_000001', '카메룬' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 188);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('CV_000000', '카보베르데', 'Cabo Verde', 'CBO_000001', '카보베르데' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 189);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('KZ_000000', '카자흐스탄', 'Kazakhstan', 'CBO_000001', '카자흐스탄' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 190);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('QA_000000', '카타르', 'Qatar', 'CBO_000001', '카타르' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 191);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('KH_000000', '캄보디아', 'Cambodia', 'CBO_000001', '캄보디아' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 192);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('CA_000000', '캐나다', 'Canada', 'CBO_000001', '캐나다' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 193);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('KE_000000', '케냐', 'Kenya', 'CBO_000001', '케냐' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 194);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('KY_000000', '케이맨 제도', 'Cayman Islands', 'CBO_000001', '케이맨 제도' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 195);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('KM_000000', '코모로', 'Comoros', 'CBO_000001', '코모로' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 196);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('CR_000000', '코스타리카', 'Costa Rica', 'CBO_000001', '코스타리카' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 197);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('CC_000000', '코코스 제도', 'Cocos (Keeling) Islands', 'CBO_000001', '코코스 제도' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 198);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('CI_000000', '코트디부아르', 'Côte d'Ivoire', 'CBO_000001', '코트디부아르' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 199);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('CO_000000', '콜롬비아', 'Colombia', 'CBO_000001', '콜롬비아' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 200);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('CG_000000', '콩고 공화국', 'Congo', 'CBO_000001', '콩고 공화국' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 201);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('CD_000000', '콩고 민주 공화국', 'Congo (Democratic Republic of the)', 'CBO_000001', '콩고 민주 공화국' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 202);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('CU_000000', '쿠바', 'Cuba', 'CBO_000001', '쿠바' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 203);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('KW_000000', '쿠웨이트', 'Kuwait', 'CBO_000001', '쿠웨이트' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 204);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('CK_000000', '쿡 제도', 'Cook Islands', 'CBO_000001', '쿡 제도' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 205);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('HR_000000', '크로아티아', 'Croatia', 'CBO_000001', '크로아티아' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 206);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('CX_000000', '크리스마스 섬', 'Christmas Island', 'CBO_000001', '크리스마스 섬' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 207);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('KG_000000', '키르기스스탄', 'Kyrgyzstan', 'CBO_000001', '키르기스스탄' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 208);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('KI_000000', '키리바시', 'Kiribati', 'CBO_000001', '키리바시' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 209);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('CY_000000', '키프로스', 'Cyprus', 'CBO_000001', '키프로스' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 210);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('TH_000000', '타이', 'Thailand', 'CBO_000001', '타이' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 211);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('TJ_000000', '타지키스탄', 'Tajikistan', 'CBO_000001', '타지키스탄' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 212);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('TZ_000000', '탄자니아', 'Tanzania, United Republic of', 'CBO_000001', '탄자니아' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 213);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('TC_000000', '터크스 케이커스 제도', 'Turks and Caicos Islands', 'CBO_000001', '터크스 케이커스 제도' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 214);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('TR_000000', '터키', 'Turkey', 'CBO_000001', '터키' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 215);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('TG_000000', '토고', 'Togo', 'CBO_000001', '토고' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 216);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('TK_000000', '토켈라우', 'Tokelau', 'CBO_000001', '토켈라우' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 217);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('TO_000000', '통가', 'Tonga', 'CBO_000001', '통가' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 218);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('TM_000000', '투르크메니스탄', 'Turkmenistan', 'CBO_000001', '투르크메니스탄' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 219);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('TV_000000', '투발루', 'Tuvalu', 'CBO_000001', '투발루' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 220);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('TN_000000', '튀니지', 'Tunisia', 'CBO_000001', '튀니지' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 221);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('TT_000000', '트리니다드 토바고', 'Trinidad and Tobago', 'CBO_000001', '트리니다드 토바고' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 222);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('PA_000000', '파나마', 'Panama', 'CBO_000001', '파나마' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 223);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('PY_000000', '파라과이', 'Paraguay', 'CBO_000001', '파라과이' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 224);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('PK_000000', '파키스탄', 'Pakistan', 'CBO_000001', '파키스탄' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 225);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('PG_000000', '파푸아 뉴기니', 'Papua New Guinea', 'CBO_000001', '파푸아 뉴기니' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 226);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('PW_000000', '팔라우', 'Palau', 'CBO_000001', '팔라우' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 227);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('PS_000000', '팔레스타인', 'Palestine, State of', 'CBO_000001', '팔레스타인' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 228);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('FO_000000', '페로 제도', 'Faroe Islands', 'CBO_000001', '페로 제도' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 229);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('PE_000000', '페루', 'Peru', 'CBO_000001', '페루' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 230);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('PT_000000', '포르투갈', 'Portugal', 'CBO_000001', '포르투갈' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 231);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('FK_000000', '포클랜드 제도', 'Falkland Islands (Malvinas)', 'CBO_000001', '포클랜드 제도' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 232);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('PL_000000', '폴란드', 'Poland', 'CBO_000001', '폴란드' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 233);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('PR_000000', '푸에르토리코', 'Puerto Rico', 'CBO_000001', '푸에르토리코' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 234);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('FR_000000', '프랑스', 'France', 'CBO_000001', '프랑스' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 235);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('GF_000000', '프랑스령 기아나', 'French Guiana', 'CBO_000001', '프랑스령 기아나' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 236);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('TF_000000', '프랑스령 남방 및 남극', 'French Southern Territories', 'CBO_000001', '프랑스령 남방 및 남극' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 237);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('PF_000000', '프랑스령 폴리네시아', 'French Polynesia', 'CBO_000001', '프랑스령 폴리네시아' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 238);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('FJ_000000', '피지', 'Fiji', 'CBO_000001', '피지' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 239);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('FI_000000', '핀란드', 'Finland', 'CBO_000001', '핀란드' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 240);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('PH_000000', '필리핀', 'Philippines', 'CBO_000001', '필리핀' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 241);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('PN_000000', '핏케언 제도', 'Pitcairn', 'CBO_000001', '핏케언 제도' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 242);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('HM_000000', '허드 맥도널드 제도', 'Heard Island and McDonald Islands', 'CBO_000001', '허드 맥도널드 제도' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 243);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('HU_000000', '헝가리', 'Hungary', 'CBO_000001', '헝가리' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 244);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('HK_000000', '홍콩', 'Hong Kong', 'CBO_000001', '홍콩' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 245);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('BQ_000000', '보나이러, 신트유스타티우스, 사바 섬', 'Bonaire, Sint Eustatius and Saba', 'CBO_000001', '보나이러, 신트유스타티우스, 사바 섬' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 246);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('CW_000000', '퀴라소', 'Curaçao', 'CBO_000001', '퀴라소' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 247);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('BL_000000', '생바르텔레미', 'Saint Barthélemy', 'CBO_000001', '생바르텔레미' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 248);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('MF_000000', '세인트마틴(프랑스령)', 'Saint Martin (French part)', 'CBO_000001', '세인트마틴(프랑스령)' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 249);

INSERT INTO TB_HC_CODE_INFO
( CODE_SQ, CODE_NM, CODE_ENG_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID, USE_YN, CODE_ORDER_NO)
VALUES ('SX_000000', '신트마르텐(네덜란드령)', 'Sint Maarten (Dutch part)', 'CBO_000001', '신트마르텐(네덜란드령)' , '2',  NOW(),'superadmin',NOW(),'superadmin', 'Y', 250);

