var XFrameViewer = document.createElement('<OBJECT ID="XFrameViewer" CLASSID="CLSID:525CE85A-4C03-49a2-BB50-DB94C12F8446" width=100% height=100% VIEWASTEXT></OBJECT>');

var myParam1  = document.createElement('<PARAM NAME="APPPATH" VALUE="C:\\xFrame">');
var myParam2  = document.createElement('<PARAM NAME="APPNAME" VALUE="XADMIN">');
var myParam3  = document.createElement('<PARAM NAME="SCREENSOURCE" VALUE="LOCAL">');
var myParam4  = document.createElement('<PARAM NAME="SCREENURL" VALUE="D:\\cosmos_client\\workspace\\korail_bz\\was">');
var myParam5  = document.createElement('<PARAM NAME="SCREENPROJECT" VALUE="xadmin">');
var myParam6  = document.createElement('<PARAM NAME="MAINFRAMESCREEN" VALUE="/xdataset">');
var myParam7  = document.createElement('<PARAM NAME="TERMINALMODE" VALUE="DEVELOPMENT">');
var myParam8  = document.createElement('<PARAM NAME="EXCLUSIVE_MODE" VALUE="TRUE">');
var myParam9  = document.createElement('<PARAM NAME="BROWSER_MENUBAR" VALUE="TRUE">');
var myParam10 = document.createElement('<PARAM NAME="BROWSER_TOOLBAR" VALUE="TRUE">');
var myParam11 = document.createElement('<PARAM NAME="BROWSER_ADDRESSBAR" VALUE="TRUE">');
var myParam12 = document.createElement('<PARAM NAME="BROWSER_STATUSBAR" VALUE="TRUE">');
var myParam13 = document.createElement('<PARAM NAME="BROWSERWIDTH" VALUE="1024">');
var myParam14 = document.createElement('<PARAM NAME="BROWSERHEIGHT" VALUE="728">');
var myParam15 = document.createElement('<PARAM NAME="WORKINGDIR" VALUE="C:\\xFrame\\bin\\">');
var myParam16 = document.createElement('<PARAM NAME="USE_CACHE" VALUE="FALSE">');
var myParam17 = document.createElement('<PARAM NAME="SHOW_CONSOLETRACE" VALUE="TRUE">');
var myParam18 = document.createElement('<PARAM NAME="BROWSER_RESIZE" VALUE="FALSE">');
var myParam19 = document.createElement('<PARAM NAME="BORDERCOLOR_FOCUS" VALUE="87,140,255">');
var myParam20 = document.createElement('<PARAM NAME="FOCUS_ROTATE" VALUE="TRUE">');
var myParam21 = document.createElement('<PARAM NAME="XDATASET_BASEURL" VALUE="http://10.141.25.13:8083/xadmin/XBizGate">');
var myParam22 = document.createElement('<PARAM NAME="FILE_UPLOAD_URL" VALUE="http://10.141.25.13:8083/xadmin/WebFileManagerForAdmin.jsp">');
var myParam23 = document.createElement('<PARAM NAME="XFRAME_VERSION_HOME_URL" VALUE="http://10.141.25.13:8083/xadmin/version">');
var myParam24 = document.createElement('<PARAM NAME="XADMIN_RUN_MODE" VALUE="DEV">');
var myParam25 = document.createElement('<PARAM NAME="XADMIN_DEMO_MODE" VALUE="FALSE">');

XFrameViewer.appendChild(myParam1);
XFrameViewer.appendChild(myParam2);
XFrameViewer.appendChild(myParam3);
XFrameViewer.appendChild(myParam4);
XFrameViewer.appendChild(myParam5);
XFrameViewer.appendChild(myParam6);
XFrameViewer.appendChild(myParam7);
XFrameViewer.appendChild(myParam8);
XFrameViewer.appendChild(myParam9);
XFrameViewer.appendChild(myParam10);
XFrameViewer.appendChild(myParam11);
XFrameViewer.appendChild(myParam12);
XFrameViewer.appendChild(myParam13);
XFrameViewer.appendChild(myParam14);
XFrameViewer.appendChild(myParam15);
XFrameViewer.appendChild(myParam16);
XFrameViewer.appendChild(myParam17);
XFrameViewer.appendChild(myParam18);
XFrameViewer.appendChild(myParam19);
XFrameViewer.appendChild(myParam20);
XFrameViewer.appendChild(myParam21);
XFrameViewer.appendChild(myParam22);
XFrameViewer.appendChild(myParam23);
XFrameViewer.appendChild(myParam24);
XFrameViewer.appendChild(myParam25);

Layer0.appendChild(XFrameViewer);

