CREATE TABLE TB_FR_DEPT_USER_MAP (
  DEPT_SQ VARCHAR(10) NOT NULL,
  USER_SQ VARCHAR(10) NOT NULL,
  DESCRIPTION VARCHAR(2000) NULL,
  CREATE_DT DATE NULL,
  CREATE_USR_ID VARCHAR(35) NULL,
  UPDATE_DT DATE NULL,
  UPDATE_USR_ID VARCHAR(35) NULL,
  PRIMARY KEY (USER_SQ),
  CONSTRAINT DEPT_SQ
    FOREIGN KEY (DEPT_SQ)
    REFERENCES TB_FR_DEPT_INFO (DEPT_SQ)
);