CREATE TABLE TB_FR_MULTI_MESSAGE_INFO (
  MESSAGE_KEY VARCHAR(100)   NOT NULL  ,
  COUNTRY_CD VARCHAR(2) NOT NULL ,
  MESSAGE_VALUE  VARCHAR(300) NOT NULL ,
  CREATE_USR_ID VARCHAR(20) DEFAULT NULL,
  CREATE_DT DATETIME DEFAULT NULL,
  UPDATE_USR_ID VARCHAR(20) DEFAULT NULL,
  UPDATE_DT DATETIME DEFAULT NULL,
   PRIMARY KEY (MESSAGE_KEY, COUNTRY_CD),
    FOREIGN KEY (MESSAGE_KEY) REFERENCES TB_FR_MESSAGE_INFO (MESSAGE_KEY),
    FOREIGN KEY (COUNTRY_CD)   REFERENCES TB_FR_LANGUAGE_INFO (LANGUAGE_ID)
);
