CREATE TABLE TB_FR_MENU_AUTH_MAP (
	WORKGROUP_SQ VARCHAR(10) NOT NULL,
	MENU_SQ VARCHAR(10) NOT NULL,
	READ_YN INT DEFAULT 0,
	UPDATE_YN INT DEFAULT 0,
	EXECUTE_YN INT DEFAULT 0,
	CREATE_DT DATETIME DEFAULT NULL,
	CREATE_USR_ID VARCHAR(20) DEFAULT NULL,
	UPDATE_DT DATETIME DEFAULT NULL,
	UPDATE_USR_ID VARCHAR(20) DEFAULT NULL,
	PRIMARY KEY (WORKGROUP_SQ, MENU_SQ),
	FOREIGN KEY (WORKGROUP_SQ) REFERENCES TB_FR_WORKGROUP_INFO(WORKGROUP_SQ),
	FOREIGN KEY (MENU_SQ) REFERENCES TB_FR_MENU_INFO(MENU_SQ)
);