CREATE TABLE TB_FR_ROLE_INFO (
  ROLE_SQ VARCHAR(10) NOT NULL,
  ROLE_ID VARCHAR(30) NOT NULL,
  ROLE_NM VARCHAR(30) NULL,
  DESCRIPTION VARCHAR(2000) NULL DEFAULT NULL,
  USE_YN VARCHAR(1) NULL,
  CREATE_DT DATETIME NULL DEFAULT NULL,
  CREATE_USR_ID VARCHAR(20) NULL DEFAULT NULL,
  UPDATE_DT DATETIME NULL DEFAULT NULL,
  UPDATE_USR_ID VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (ROLE_SQ)
);