--DROP TABLE   TB_FR_DEPT_INFO;
CREATE TABLE TB_FR_DEPT_INFO (
  DEPT_SQ VARCHAR(10) NOT NULL,
  DEPT_ID VARCHAR(20) NOT NULL,
  DEPT_NM VARCHAR(50) NOT NULL,
  DESCRIPTION VARCHAR(500) NOT NULL,
  PARENT_DEPT VARCHAR(10) NOT NULL,
  DEPT_PRIOITY INT NULL,
  STATUS_CD VARCHAR(10)  DEFAULT 'Y',
  CREATE_USR_ID VARCHAR(45)  DEFAULT NULL,
  CREATE_DT DATE  DEFAULT NULL,
  UPDATE_USR_ID VARCHAR(45)  DEFAULT NULL,
  UPDATE_DT DATE DEFAULT NULL,
  PRIMARY KEY (DEPT_SQ)
 );
