CREATE TABLE TB_FR_ROLE_INFO (
  ROLE_SQ VARCHAR(10) NOT NULL,
  ROLE_ID VARCHAR(30) NOT NULL,
  ROLE_NM VARCHAR(30)  DEFAULT NULL,
  DESCRIPTION VARCHAR(2000)  DEFAULT NULL,
  USE_YN VARCHAR(1)  DEFAULT 'Y',
  CREATE_DT DATE  DEFAULT NULL,
  CREATE_USR_ID VARCHAR(20)  DEFAULT NULL,
  UPDATE_DT DATE  DEFAULT NULL,
  UPDATE_USR_ID VARCHAR(20)  DEFAULT NULL,
  PRIMARY KEY (ROLE_SQ)
);


