
CREATE TABLE TB_FR_USER_ROLE_MAP (
  USER_SQ VARCHAR(10) NOT NULL,
  ROLE_SQ VARCHAR(10) NOT NULL,
  DESCRIPTION VARCHAR(2000) NULL,
  CREATE_DT DATE NULL,
  CREATE_USR_ID VARCHAR(35) NULL,
  UPDATE_DT DATE NULL,
  UPDATE_USR_ID VARCHAR(35) NULL,
  PRIMARY KEY (USER_SQ, ROLE_SQ),
    FOREIGN KEY (USER_SQ) REFERENCES TB_FR_USER_INFO (USER_SQ),
   FOREIGN KEY (ROLE_SQ)  REFERENCES TB_FR_ROLE_INFO (ROLE_SQ)
);




