
CREATE TABLE TB_FR_MENU_INFO (
  MENU_SQ VARCHAR(10) PRIMARY KEY  NOT NULL  ,
  MENU_NM VARCHAR(50) NOT NULL ,
  PARENT_MENU_SQ VARCHAR(10) NOT NULL ,
  MENU_URL VARCHAR(1000)  ,
  MENU_LEVEL_NO INT NOT NULL ,
  MENU_ORDER_NO INT NOT NULL ,
  USE_YN VARCHAR(1) NOT NULL ,
  CREATE_USR_ID VARCHAR(20) DEFAULT NULL,
  CREATE_DT DATE DEFAULT NULL,
  UPDATE_USR_ID VARCHAR(20) DEFAULT NULL,
  UPDATE_DT DATE DEFAULT NULL
);