--03 예약발매 실적

SELECT RUN_DT,
        TRN_NO,
        DPT_BF_DNO,
        SUM( ACM_RSV_SEAT_CNT + ACM_SALE_SEAT_CNT - ACM_CNC_SEAT_CNT - ACM_RET_SEAT_CNT ) SUM_CNT 
  FROM TB_YD340
 WHERE RUN_DT = :AS_RUN_DT
   AND TRN_NO = :AS_TRN_NO
   AND DPT_BF_DNO >= 0 
   AND DPT_BF_DNO <= 60
--   AND DPT_STGP_CD = DECODE(:AS_DPT_STGP_CD, '%', DPT_STGP_CD, :AS_DPT_STGP_CD)
--   AND ARV_STGP_CD = DECODE(:AS_ARV_STGP_CD, '%', ARV_STGP_CD, :AS_ARV_STGP_CD)
 GROUP BY RUN_DT, TRN_NO, DPT_BF_DNO
 ORDER BY DPT_BF_DNO