
INSERT INTO TB_FR_LANGUAGE_INFO
( LANGUAGE_SQ, LANGUAGE_ID, LANGUAGE_NM, USE_YN, ORDER_NO, CREATE_DT, CREATE_USR_ID)
VALUES ('LAN_000001','KO', 'Korean',  'Y' , 0,  systimestamp,'superadmin');

INSERT INTO TB_FR_LANGUAGE_INFO
( LANGUAGE_SQ, LANGUAGE_ID, LANGUAGE_NM, USE_YN, ORDER_NO, CREATE_DT, CREATE_USR_ID)
VALUES ('LAN_000002','EN', 'English',  'Y' , 1,  systimestamp,'superadmin');

