--네이밍
---대분류 UI/SERV/COM
---중분류 TEXT/MSG
---소분류 FORM/LABEL/BTN CON/WARN/ERR/SUCC/INFO
--ID 대분류_중분류_소분류

/* UI-TEXT-FORM */
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_TEXT_FORM_NO', 'EN', 'NO',   'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_TEXT_FORM_USABLE', 'EN',  'Usable',   'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_TEXT_BTN_ADD', 'EN','Add',   'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_TEXT_BTN_EDIT', 'EN','Edit',   'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_TEXT_BTN_DEL', 'EN','Delete',   'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_TEXT_BTN_NEW','EN', 'New',   'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_TEXT_BTN_SEARCH', 'EN','search',   'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_TEXT_BTN_SAVE', 'EN','Save',   'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_TEXT_BTN_CONFIRM', 'EN','Confirm',   'superadmin', systimestamp);

INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_TEXT_FORM_DESCRIPTION', 'EN', 'Description',   'superadmin', systimestamp);




INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_MSG_WARN_KOENGNULLNUMCHECK',  'EN', 'can be  only Korean, English, numbers and  (underscore). (Period), (comma) - (hyphen), / (slash).',  'superadmin', systimestamp);

INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_MSG_WARN_ENGNUMCHECK', 'EN','can be  only English, numbers and  (underscore). (Period), (comma) - (hyphen), / (slash).',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_MSG_WARN_ENGCHECK', 'EN','can be  only  English  and  (underscore). (Period), (comma) - (hyphen), / (slash).',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_MSG_WARN_EMAILCHECK', 'EN','This email is formatted incorrectly.',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_MSG_WARN_ONLYNUMCHECK', 'EN','can be  only  numbers.',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_MSG_WARN_URLCHECK', 'EN', 'This URL is formatted incorrectly.',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_MSG_WARN_SELECTCHECK', 'EN','Please select one or more items.',  'superadmin', systimestamp);

INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_MSG_WARN_NO_SAVE_DATA', 'EN','There is no data to save.',  'superadmin', systimestamp);

INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'COM_MSG_WARN_COM_NOT_EXIST', 'EN','The value corresponding to the [ {0} ]  does not exist.',  'superadmin', systimestamp);

INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'COM_MSG_WARN_COM_ALREADY_EXIST','EN', 'The value corresponding to the [ {0} ]  does  already exist',  'superadmin', systimestamp);


INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'COM_MSG_WARN_COM_WRONG_DATA', 'EN','Incorrect value was entered in [ {0} ].',  'superadmin', systimestamp);

/* COM-MSG-ERR */
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('COM_MSG_ERR_999', 'EN','The unexpected errors occurred.',   'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('COM_MSG_ERR_998','EN', 'The results of the selected data does not exist.',   'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('COM_MSG_ERR_997','EN', 'You do not have the authority that is access to this item.',   'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('COM_MSG_ERR_995','EN', 'Errors occurred during the editing to access authority.',   'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('COM_MSG_ERR_996','EN', 'Errors occurred during to insert log.',   'superadmin', systimestamp);

INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('COM_MSG_ERR_USED_CODE', 'EN','The code is being used. Can not be deleted.',   'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('COM_MSG_ERR_FILE_NOT_EXCEL', 'EN','This file is not Excel format. Or this file is protected',   'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('COM_MSG_ERR_FAIL_LOAD_EXCEL', 'EN','Errors occurred during the loading ExcelFile.',   'superadmin', systimestamp);


INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('COM_MSG_ERR_ALREADY_DELETED', 'EN','Already The data has been deleted or not.',   'superadmin', systimestamp);

INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_TEXT_FORM_USER_ID', 'EN', 'User ID',   'superadmin', systimestamp);

INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_TEXT_FORM_MYSINGLE_ID', 'EN', 'MySingle ID',   'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_TEXT_FORM_USERNAME', 'EN', 'UserName',   'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_TEXT_FORM_ID', 'EN', 'ID',   'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_TEXT_FORM_NEW_USERNAME','EN',  'UserName',   'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_TEXT_FORM_PASSWORD','EN',  'Password',   'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_TEXT_FORM_PASSWORD_CONFIRM','EN',  'Password Confirm',   'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_TEXT_FORM_CHANGE_PASSWORD', 'EN', 'Change Password',   'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_TEXT_FORM_CHANGE_PASSWORD_CONFIRM', 'EN',  'Change Password Confirm',   'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_TEXT_FORM_WORK', 'EN', 'Work',   'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_MSG_WARN_PW_DIGITSCHECK', 'EN', ' Password is allowed to Min 8~Max 20 characters in length.
Contains 3/4 of the following items: Upper/Lowercase Letters, Numbers, Symbols.',   'superadmin', systimestamp);

INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_MSG_WARN_PW_COMBINATION_THREE_SCHECK', 'EN', 'More than 4 consecutive letter combination on keyboard is not allowed.',   'superadmin', systimestamp);


INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_MSG_WARN_PW_FOUR_CONSECUTIVE_SCHECK', 'EN','The password  must not be  more than four sequential characters. ex)abcd, 1234',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_MSG_WARN_PW_FOUR_CONTINUOUS_SCHECK', 'EN','The password must not be the same character is repeated at least four times.',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_MSG_WARN_PW_KEYBOARD_FOUR_CONTINUOUS_SCHECK', 'EN','The password is then not more than 4 consecutive characters on the keyboard. ex)qwer, asdf',  'superadmin', systimestamp);

INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_MSG_WARN_USER_IMPORT_SUCCESS_01', 'EN','Total : {0}&lt;br&gt;&lt;br&gt;',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_MSG_WARN_USER_IMPORT_SUCCESS_02', 'EN','Success : {0}',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_MSG_WARN_USER_IMPORT_FAILED_01', 'EN','Total : {0}&lt;br&gt;&lt;br&gt;',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_MSG_WARN_USER_IMPORT_FAILED_02', 'EN','Success : {0}',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_MSG_WARN_USER_IMPORT_FAILED_03', 'EN','Fail : {0}',  'superadmin', systimestamp);

INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_MSG_WARN_ONLY_SPECIFIED_FILE_POSSIBLE', 'EN','Only possible : {0} file',  'superadmin',  systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_MSG_WARN_ONLY_SPECIFIED_EXT_POSSIBLE', 'EN','Only possible extension : {0}',  'superadmin',  systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_MSG_WARN_ONLY_SPECIFIED_EXT_DENIED', 'EN','Deny extension : {0}',  'superadmin',  systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_MSG_WARN_DENIED_DUPLICATED_FILE', 'EN','Duplicated File Name : {0}&lt;br&gt; You can not upload the same file name.',  'superadmin',  systimestamp);

INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_MSG_WARN_OVERSIZE_FILE', 'EN','You cannot upload file over {0}MB',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_MSG_WARN_OVERSIZE_TOTAL_FILES', 'EN','You cannot upload over {0}MB',  'superadmin', systimestamp);

INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_MSG_CON_DELETE','EN', 'Are you sure you want to delete?',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_MSG_CON_ROLE_SAVED_DATA','EN', 'Registered data on the role exists.&lt;br&gt;Are you sure you want to delete?',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_MSG_CON_WORKGROUP_SAVED_DATA','EN', 'Registered data on the workgroup exists.&lt;br&gt;Are you sure you want to delete?',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_MSG_CON_ADD', 'EN','Do you want to add a selected list?',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_MSG_CON_SAVE', 'EN','Do you want to save the selected list?',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_MSG_CON_USER', 'EN','Do you want to confirm the selected user list?',  'superadmin', systimestamp);



INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_TEXT_FORM_USERSTATUS', 'EN', 'User Status',   'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_TEXT_FORM_GRD', 'EN', 'Position',   'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_TEXT_FORM_DEPT', 'EN', 'Department',   'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_TEXT_FORM_DEPT_NM', 'EN', 'Dept Name',   'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_TEXT_FORM_AGE','EN',  'Age',   'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_TEXT_FORM_BIRTH', 'EN', 'Date of birth',   'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_TEXT_FORM_JOINYMD', 'EN', 'Accession date',   'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_TEXT_FORM_ROLE_ID', 'EN', 'Role ID',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_TEXT_FORM_ROLE_NM','EN',  'Role Name',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_TEXT_FORM_MENU_NM', 'EN', 'Menu Name',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_TEXT_FORM_MENU_LEVEL','EN', 'Menu Level',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_TEXT_FORM_MENU_ORDER', 'EN', 'Menu Order',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_TEXT_FORM_MENU_ID','EN',  'Menu ID',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_TEXT_FORM_EMAIL', 'EN', 'email',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_TEXT_FORM_PHONENUM', 'EN',  'Phone number',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_TEXT_FORM_WORKGROUP_ID', 'EN', 'Workgroup ID',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_TEXT_FORM_WORKGROUP_NM', 'EN', 'Workgroup Name ',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_TEXT_FORM_STATUS','EN',  'status',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_TEXT_FORM_CODE_ID', 'EN', 'Code ID',   'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_TEXT_FORM_CODE_NM', 'EN', 'Code Name',   'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_TEXT_FORM_CODE_LEVEL','EN',  'Code Level', 'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_TEXT_FORM_CODE_ORDER', 'EN', 'Code Order', 'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_TEXT_FORM_ROLE', 'EN', 'Role',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_TEXT_FORM_TYPE', 'EN', 'type',  'superadmin', systimestamp);

INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_TEXT_FORM_URL','EN',  'URL',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_TEXT_BTN_MENU_PAGE_SAVE','EN',  'Menu Page Save',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_TEXT_FORM_MENU', 'EN', 'Menu',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_TEXT_FORM_READ', 'EN', 'Read',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_TEXT_FORM_UPDATE', 'EN', 'Update',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_TEXT_FORM_EXECUTE', 'EN', 'excute',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_TEXT_FORM_WORKGROUP', 'EN', 'workgroup',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_TEXT_FORM_SENDER', 'EN', 'Sender',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_TEXT_FORM_RECEIVER', 'EN', 'Receivers',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_TEXT_FORM_MAILTITLE', 'EN', 'Title',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_TEXT_FORM_MAILCONTENT', 'EN', 'Content',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_TEXT_FORM_ATTACHMENT', 'EN', 'Attachments',  'superadmin', systimestamp);

/* UI-TEXT-LABEL */
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_TEXT_LABEL_ADD_USER',  'EN','Add User',   'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_TEXT_LABEL_SIGNIN_USER',  'EN','Sign Up',   'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_TEXT_LABEL_EDIT_USER',  'EN','Edit User',   'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_TEXT_LABEL_EDIT_MYINFO',  'EN','Edit My Info',   'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_TEXT_LABEL_DEL_ROLE',  'EN','Delete Role',   'superadmin', systimestamp);


INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_TEXT_LABEL_MENU_TREE', 'EN', 'Menu List',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_TEXT_LABEL_MENU_INFO',  'EN','Menu Info',  'superadmin', systimestamp);

INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_TEXT_LABEL_USER_SEARCH', 'EN', 'Search User',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_TEXT_LABEL_WORKGROUP_SEARCH',  'EN','Search Workgroup',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_TEXT_LABEL_WORKGROUP_MENU',  'EN','Menu Management By Workgroup',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_TEXT_LABEL_WORKGROUP_USER',  'EN','User Management By Workgroup',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_TEXT_LABEL_WORKGROUP_ROLE',  'EN','Role Management By Workgroup',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_TEXT_LABEL_ADD_ROLE',  'EN','Add Role',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_TEXT_LABEL_EDIT_ROLE',  'EN','Edit Role',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_TEXT_LABEL_EDIT_MENU',  'EN','Edit Menu',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_TEXT_LABEL_ADD',  'EN','Add',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_TEXT_LABEL_ROLE_USER_MGN',  'EN','User Management By Role',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_TEXT_LABEL_ROLE_MGN',  'EN','Role Management',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_TEXT_LABEL_WORKGROUP_MGN',  'EN','Workgroup Management',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_TEXT_LABEL_LOG_MGN',  'EN',' Access history Management',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_TEXT_LABEL_WORK_LOG_MGN',  'EN','Work history Management',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_TEXT_LABEL_ETC_MGN',  'EN','Other Management',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_TEXT_LABEL_CODE_MGN',  'EN','Code Management',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_TEXT_LABEL_MGN_FUNC',  'EN','Management Function',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_TEXT_LABEL_ROLE_WORKGROUP_MGN', 'EN', 'Workgroup Management By Role',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_TEXT_LABEL_MESSAGE_MGN',  'EN','Message Management',  'superadmin', systimestamp);

INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_TEXT_FORM_MESSAGE_KEY',  'EN', 'Key',  'superadmin', systimestamp);

INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_TEXT_FORM_MESSAGE_VALUE',  'EN',  'Value',  'superadmin', systimestamp);

INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_TEXT_FORM_MESSAGE_LARGE_CATEGORY', 'EN', 'Large',  'superadmin', systimestamp);

INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_TEXT_FORM_MESSAGE_MEDIUM_CATEGORY', 'EN','Medium',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_TEXT_FORM_MESSAGE_SMALL_CATEGORY', 'EN', 'Small',  'superadmin', systimestamp);

INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_TEXT_FORM_LOG_SQ', 'EN', 'Log Sequence',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_TEXT_FORM_EVENT_IP', 'EN','IP Address',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_TEXT_FORM_EVENT_DT','EN', 'Log occurrence time',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_TEXT_FORM_EVENT_NO', 'EN','Event',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_TEXT_FORM_LOG_MSG', 'EN','Log Management',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_TEXT_FORM_LOGIN_SUCC', 'EN', 'Login',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_TEXT_FORM_LOGOUT', 'EN','Logout',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_TEXT_FORM_LOGIN_FAIL', 'EN','Login Fail',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_TEXT_LABEL_MENU_PAGE_LIST', 'EN','Menu Page List',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_TEXT_LABEL_MENU_AUTH_MGN','EN', 'Menu/Role Management',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_TEXT_LABEL_WORKGROUP_DEL', 'EN', 'Delete Workgroup',   'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_TEXT_LABEL_WORKGROUP_EDIT', 'EN','Edit Workgroup',   'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_TEXT_LABEL_MENU_DEL', 'EN','Delete Menu',   'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_TEXT_LABEL_MENU_SAVE', 'EN','Save Menu',   'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_TEXT_LABEL_DEL', 'EN','Delete',   'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_TEXT_FORM_CREATE_USR_ID', 'EN','Author',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_TEXT_FORM_CREATE_DT', 'EN','Date of registration',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_TEXT_FORM_UPDATE_USR_ID', 'EN','Modifier',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_TEXT_FORM_UPDATE_DT','EN' , 'Date of modification',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_TEXT_LABEL_CODE_TREE', 'EN','Code List',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_TEXT_LABEL_CODE_INFO', 'EN','Code Detail Information',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_TEXT_LABEL_ADD_MENU', 'EN','Add Menu',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_TEXT_LABEL_WORKGROUP_ADD', 'EN','Add Workgroup',  'superadmin', systimestamp);

INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_TEXT_LABEL_ADD_MESSAGE', 'EN','Add Message',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_TEXT_LABEL_EDIT_MESSAGE','EN', 'Edit Message',  'superadmin', systimestamp);

INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_TEXT_LABEL_SEND_MAIL','EN', 'Send Mail',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_TEXT_LABEL_SEND_MAIL_SUCCESS','EN', 'Send Mail Success',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_TEXT_LABEL_SEND_MAIL_FAIL','EN', 'Send Mail Failed',  'superadmin', systimestamp);


/* UI-TEXT-BTN */
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_TEXT_BTN_ROLE_NAME', 'EN','Role Name',   'superadmin', systimestamp);

INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_TEXT_BTN_CODE_SAVE', 'EN','Code Information Save',   'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_TEXT_BTN_USER', 'EN','User',   'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_TEXT_BTN_MENU', 'EN','Menu',   'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_TEXT_BTN_ROLE', 'EN','Role',   'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_TEXT_BTN_EXPANDALL', 'EN','expand all',   'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_TEXT_BTN_COLLAPSEALL','EN', 'collapse all',   'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_TEXT_BTN_MENU_INFO_SAVE', 'EN','Save Menu Information',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_TEXT_BTN_SELECT', 'EN','Select',   'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_TEXT_BTN_CLOSE', 'EN','Close',   'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_TEXT_BTN_LIST', 'EN','List',   'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_TEXT_BTN_SENDMAIL', 'EN','SendMail',   'superadmin', systimestamp);

INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_TEXT_DOWNLOAD_FORMAT', 'EN','Download Format',   'superadmin', systimestamp );
/* UI-TEXT-CON */
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_TEXT_CON_SAVE_COOKIE', 'EN','Do you want to save the ID?',   'superadmin', systimestamp);

/* UI-TEXT-WARN */

INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_TEXT_WARN_CURUSER_DELETE', 'EN','You can not delete yourself.',   'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_TEXT_WARN_CONFIRM_USER', 'EN','It failed on user confirmation.',   'superadmin', systimestamp);


/* UI-TEXT-ERR */
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('SERV_TEXT_ERR_LOGIN','EN', 'The ID or password is incorrect.',   'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('SERV_TEXT_ERR_ACCOUNT_LOCK', 'EN','This account has been locked in a password more than five times the error.',   'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('SERV_TEXT_ERR_ACCOUNT_NO_ROLE', 'EN','The user does not have a available role',   'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('SERV_TEXT_ERR_ACCOUNT_ON_WAITING', 'EN','It is awaiting approval.',   'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('SERV_TEXT_ERR_LOGIN_WITHDRAW', 'EN','The user is a withdrawal user.',   'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('SERV_TEXT_ERR_LOCKED_USER', 'EN','The user is a locked user.',   'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('SERV_TEXT_ERR_LOGIN_DUP','EN', 'A duplicate account with the same login ID will be logged out of the browser occurred.',   'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_TEXT_ERR_BOTH_PERIOD', 'EN','For a period of search, you must enter both the start date and end date.',   'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_TEXT_ERR_START_EARLY', 'EN', 'Start date and end date is equal to or fast.',   'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_TEXT_ERR_NOW_EARLY', 'EN','Start date, end date will be fast or equal to the current date.',   'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_TEXT_ERR_NOT_EXIST_USER', 'EN','The Sender Information is not exist!',   'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_TEXT_ERR_WRONG_IP_ADDRESS', 'EN','In this system, you can not send mail.&lt;br&gt;Please contact your administrator.',   'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_TEXT_ERR_ESB', 'EN', 'Errors occurred during the sending email.',   'superadmin', systimestamp);

INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_MSG_WARN_NO_SELECT_MENU','EN', 'Please select the first menu in the menu list.',   'superadmin', systimestamp);

INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_MSG_WARN_MENUMGN_NO_ADD_MORE_TWO', 'EN','Menu can only register once.',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_MSG_CON_MENUMGN_NO_SAVED_MENU', 'EN','Unsaved new menu will be deleted. Are you sure you want to proceed?',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_MSG_WARN_MENUMGN_NO_SELECTED_MENU_ADD', 'EN','Please select the top menu on the menu to add.',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_MSG_WARN_MENUMGN_NO_SELECTED_MENU_DELETE', 'EN','Please select the delete menu.',  'superadmin', systimestamp);

INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_MSG_WARN_WRONG_KOENGNULLNUMCHECK', 'EN', '[ {0} ]  can be  only  Korean, English ,numbers and  (underscore). (Period), (comma) - (hyphen), / (slash) () (parenthesis) .',  'superadmin', systimestamp);


INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_MSG_WARN_CODEMGN_NO_SAVED_CODE','EN','Please save from the code.',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_MSG_WARN_CODEMGN_NO_ADD_MORE_TWO', 'EN','The code can only register once.',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_MSG_WARN_CODEMGN_NO_SAVED_MOVE_CODE', 'EN','Please go and save the code.',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_MSG_WARN_MENUMGN_NO_SELECTED_MENU', 'EN','The menu is not selected.',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_MSG_WARN_MENUMGN_NO_TOPMENU_DRAG', 'EN','You can not move the top menu.',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_MSG_WARN_NOT_CHANGED', 'EN','No data has changed.',  'superadmin', systimestamp);

INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'COM_MSG_WARN_MENU_ORDER_LIMITS', 'EN','Menu order is available 1-20.',  'superadmin', systimestamp);

INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'SERV_MSG_WARN_DELETE_MENU', 'EN', 'the menu is deleted.',  'superadmin', systimestamp);

INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'SERV_MSG_WARN_CANNOT_UPDATE', 'EN', 'This data can not be updated.',  'superadmin', systimestamp);

INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_MSG_WARN_REQUIRED', 'EN','is the required value.',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_MSG_WARN_PHONECHECK', 'EN', 'This phone number format is invalid.',  'superadmin', systimestamp);


INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_MSG_WARN_ENGNUMSPCCHARCHECK', 'EN',' can be  only  English and numbers and  (underscore). (Period), (comma) - (hyphen), / (slash). () (parenthesis) .',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_MSG_WARN_CORRECTKOENGNULLNUMCHECK','EN', 'can be  only perfect Korean, English ,numbers and  (underscore). (Period), (comma) - (hyphen), / (slash). () (parenthesis) .',  'superadmin', systimestamp);

INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_MSG_WARN_NOT_EXIST_ADD', 'EN','You no longer have to add the menu.',  'superadmin', systimestamp);

INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_MSG_WARN_ADD_MENU_NO_PARENT','EN', 'You must first save the upper menu.',   'superadmin', systimestamp);

INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'COM_MSG_WARN_COM_REQUIRED','EN', '[ {0} ] is the required value.',  'superadmin', systimestamp);

INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_MSG_WARN_PASSWORD_NOT_EQUAL', 'EN','[Password] Password and Password Confirm are not the same.',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_MSG_WARN_PASSWORD_NOT_CORRECT', 'EN','[Password] The password is wrong.',  'superadmin', systimestamp);

INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_MSG_WARN_IDCHECK_REQUIRED', 'EN','[ID Check] Press the button, you need to check the ID.',  'superadmin', systimestamp);

INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_MSG_WARN_KEY_REQUIRED', 'EN','[Key Check] Press the button, you need to check the Key.',  'superadmin', systimestamp);

INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_MSG_WARN_KEY_NOT_EXIST', 'EN','[Key] is the required value.',  'superadmin', systimestamp);

INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_MSG_WARN_ID_AVAILABLE', 'EN', 'It is available ID.',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_MSG_WARN_KEY_AVAILABLE', 'EN', 'It is available Key.',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_MSG_WARN_ID_DUPLICATED','EN', 'It is duplicate ID.',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_MSG_WARN_KEY_DUPLICATED','EN', 'It is duplicate Key.',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_MSG_WARN_NOT_EXIST_MENU_NM', 'EN','The menu containing the search term does not exist.',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'SERV_MSG_WARN_MENUMGN_NO_TOPMENU_UPDATE', 'EN','You can not modify the top-level menu.',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('SERV_MSG_WARN_TEXT_LENGTH_LIMITS', 'EN', 'The [ {0} ] can be input up to {0} length. ',   'superadmin', systimestamp);


INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'SERV_MSG_INFO_PASSWORD_INFO_MAIL_TITLE', 'EN','New password will be sent to new users.',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('SERV_MSG_INFO_PASSWORD_INFO_MAIL_CONTENT', 'EN', ' - This is a temporary password for guidance.&lt;br&gt;&lt;br&gt;Please modify the password after you log in. &lt;br&gt;&lt;br&gt; Temporary Password : ',   'superadmin', systimestamp);


INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('COM_TEXT_LABEL_AUTO_MENU_ID', 'EN','{0} is generated automatically.',  'superadmin', systimestamp);

INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('COM_MSG_WARN_MENU_LEVEL_LIMITS', 'EN','Menu level is available 1-3.',   'superadmin', systimestamp);

INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('COM_MSG_WARN_MENU_URL_REQUIRED', 'EN','If the menu level is 3,  Menu  URL is a required value.',   'superadmin', systimestamp);

INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('COM_MSG_WARN_1_LEVEL_MENU_LIMITS', 'EN','If the menu level 1 you can save up to five',   'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'COM_MSG_WARN_MENUMGN_NO_TOPMENU_DELETE', 'EN','You can not delete the top-level menu.',  'superadmin', systimestamp);

INSERT INTO TB_FR_MULTI_MESSAGE_INFO( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_MSG_WARN_SUCC_MENU_DRAG_DROP_SUCC', 'EN','The menu has changed location. After the menu is reflected in the information storage.',   'superadmin', systimestamp);


INSERT INTO TB_FR_MULTI_MESSAGE_INFO( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_MSG_WARN_MENU_PAGE_INSERT_NO_MENUSQ','EN', 'you first must be saved menu before adding  menu page.',   'superadmin', systimestamp);

INSERT INTO TB_FR_MULTI_MESSAGE_INFO( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_MSG_WARN_MENU_PAGE_INSERT_NO_MENUURL', 'EN','If there is no menu URL, You can not add menu page. ',   'superadmin', systimestamp);

INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'COM_MSG_WARN_MENUMGN_MENU_UPDATE_HASITEMS', 'EN','If the menu has a submenu, you can not change the menu level.',  'superadmin', systimestamp);



INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_MSG_SUCC_SAVED_MENU', 'EN','It has been saved successfully. The stored menu  will reflect upon reloading.',  'superadmin', systimestamp);

INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'COM_MSG_WARN_ROLEMGN_CANNOT_DELETE_ADMIN_ROLE', 'EN','System Administrator role can not be deleted.',  'superadmin', systimestamp);

INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'COM_MSG_WARN_WORKGROUP_CANNOT_DELETE_ADMIN_WORKGROUP', 'EN','System Administrator workgroup can not be deleted.',  'superadmin', systimestamp);



/* COM-MSG-WARN */
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'COM_MSG_WARN_MENUMGN_MENU_DELETE_HASITEMS', 'EN','If the menu has a submenu, you can not delete.',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'COM_MSG_WARN_CODEMGN_CODE_DELETE_HASITEMS','EN', 'If the code has a subcode, you can not delete.',  'superadmin', systimestamp);

--INSERT INTO TB_FR_MULTI_MESSAGE_INFO
--( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
--VALUES ('COM_MSG_ERR_996', 'EN','The code is being used. Can not be deleted.',   'superadmin', systimestamp);

/* COM-MSG-SUCC */
/* COM-MSG-INFO */


INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_MSG_SUCC_SAVE', 'EN','It has been saved successfully.',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_MSG_SUCC_ADD', 'EN','It has been added successfully.',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_MSG_DEL_SAVE', 'EN','It has been deleted successfully',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_MSG_DEL_FAIL', 'EN','You can not delete.',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_MSG_EDIT_FAIL', 'EN','You can not modify.',  'superadmin', systimestamp);


INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_MSG_WARN_NO_SELECTED_DELETE_DATA', 'EN','Please select the data to be deleted.',  'superadmin', systimestamp);

INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('SERV_MSG_ERR_NO_ROLE', 'EN','You do not have permission to this page.',  'superadmin', systimestamp);




INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ( 'UI_TEXT_LABEL_CHANGE_USER', 'EN','Change User',  'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_TEXT_BTN_CHANGE', 'EN','Change',   'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_TEXT_BTN_EXIT', 'EN','End',   'superadmin', systimestamp);
INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_MSG_WARN__NO_SIGN_MYSINGE_SSO', 'EN','There is not SSO information, go to the login page. Let you like to continue?',   'superadmin', systimestamp);

INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)

VALUES ('UI_MSG_WARN_NO_IE_MYSINGE_SSO', 'EN','The system can be connected only with Internet Explorer 11.',   'superadmin', systimestamp);

INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_MSG_WARN_NOT_EXIST_USER_ID', 'EN','The user ID does not exist.',   'superadmin', systimestamp);


INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_TEXT_LABEL_USER_INFO_REG', 'EN','Registered user information',   'superadmin', systimestamp);


INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_TEXT_FORM_REAL_USER_ID', 'EN', 'Real user ID',   'superadmin', systimestamp);

INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_TEXT_LABEL_LANGUAGE', 'EN', 'Language',   'superadmin', systimestamp);


INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_TEXT_CON_CHANG_LANGUAGE', 'EN', 'If really you want to change your language? &lt;br/&gt; If language is changed,  go to the index page.',   'superadmin', systimestamp);

INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_TEXT_CON_CHANG_DEFAUT_LANGUAGE', 'EN', 'The default language is changed,,  go to the index page.',   'superadmin', systimestamp);


INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_TEXT_LABEL_SAVE_ID', 'EN', 'Save user ID',   'superadmin', systimestamp);


INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_TEXT_LABEL_JOIN_MEMBER', 'EN', 'Create account',   'superadmin', systimestamp);

INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_TEXT_LABEL_SYSTEM_CONTACT', 'EN', 'Contact information',   'superadmin', systimestamp);

INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_TEXT_SYSTEM_LICENCE', 'EN', 'this system is strictly restricted to authorized users only. any illegal access shall be punished with a related-law.',   'superadmin', systimestamp);

INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_TEXT_LABEL_METHOD_NAME', 'EN', 'Method Name',   'superadmin', systimestamp );

INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_TEXT_LABEL_WORK_LOG_DETAIL', 'EN', 'Work Log Detail',   'superadmin', systimestamp );

INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_TEXT_LABEL_COMBO_ALL', 'EN', 'All',   'superadmin', systimestamp);

INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)

VALUES ('COM_MSG_ERR_EXPIRED_SESSION', 'EN', 'Your session has expired. Would you like to go to the login page?',   'superadmin', systimestamp);

INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_TEXT_LABEL_END_IMPERSON', 'EN', 'end imperson',   'superadmin', systimestamp);

INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('SERV_TEXT_ERR_NOT_USE_THIS_FUNC', 'EN', 'The user was not able to execute this function.&lt;br&gt;(You have to register for workgroup-user or user-role.)',   'superadmin', systimestamp);

INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('SERV_TEXT_ERR_NOT_USING_USER', 'EN', 'This is not a usesr on using.',   'superadmin', systimestamp);

INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('SERV_TEXT_ERR_NOT_CHANGE_CURRENT_USER', 'EN', 'Yon can not change the current user.',   'superadmin', systimestamp);

INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('SERV_TEXT_ERR_NOT_EXIST_CHANGED_USER', 'EN', 'User information does not exist.',   'superadmin', systimestamp);

INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('SERV_TEXT_ERR_ALREADY_END_IMPERSON', 'EN', 'It is already shut down to chages a user.<br>Please press F5',   'superadmin', systimestamp);

INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_TEXT_LABEL_CHANGE_PASSWORD', 'EN', 'Change password',   'superadmin', systimestamp);

INSERT INTO TB_FR_MULTI_MESSAGE_INFO
( MESSAGE_KEY, COUNTRY_CD , MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('UI_TEXT_FORM_COUNTRY_CODE', 'EN', 'Country code',   'superadmin', systimestamp);