INSERT INTO TB_FR_DEPT_INFO (DEPT_SQ, DEPT_ID, DEPT_NM, DESCRIPTION, PARENT_DEPT, DEPT_PRIOITY, STATUS_CD, CREATE_USR_ID, CREATE_DT, UPDATE_USR_ID, UPDATE_DT) 
VALUES ('DEP0000000', 'NONE', 'NONE', '임시/혹은 부서없음', 'DEP0000000', 1, 'STS0000001', 'superadmin', systimestamp, 'superadmin',  systimestamp);

INSERT INTO TB_FR_DEPT_INFO (DEPT_SQ, DEPT_ID, DEPT_NM, DESCRIPTION, PARENT_DEPT, DEPT_PRIOITY, STATUS_CD, CREATE_USR_ID, CREATE_DT, UPDATE_USR_ID, UPDATE_DT)
VALUES ('DEP0000001', 'SDS', '삼성SDS', '최상위 부서', 'DEP0000001', 1, 'STS0000001', 'superadmin', systimestamp, 'superadmin',  systimestamp);

INSERT INTO TB_FR_DEPT_INFO (DEPT_SQ, DEPT_ID, DEPT_NM, DESCRIPTION, PARENT_DEPT, DEPT_PRIOITY, STATUS_CD, CREATE_USR_ID, CREATE_DT, UPDATE_USR_ID, UPDATE_DT)
VALUES ('DEP0000002', 'R&DCenter', '연구소', 'SDS 연구소', 'DEP0000001', 1, 'STS0000001', 'superadmin', systimestamp, 'superadmin',  systimestamp);

INSERT INTO TB_FR_DEPT_INFO (DEPT_SQ, DEPT_ID, DEPT_NM, DESCRIPTION, PARENT_DEPT, DEPT_PRIOITY, STATUS_CD, CREATE_USR_ID, CREATE_DT, UPDATE_USR_ID, UPDATE_DT)
VALUES ('DEP0000003', 'SolutionDevTeam', '솔루션개발팀', 'SDS 연구소산하 솔루션개발팀', 'DEP0000002', 1, 'STS0000001', 'superadmin', systimestamp, 'superadmin',  systimestamp);

INSERT INTO TB_FR_DEPT_INFO (DEPT_SQ, DEPT_ID, DEPT_NM, DESCRIPTION, PARENT_DEPT, DEPT_PRIOITY, STATUS_CD, CREATE_USR_ID, CREATE_DT, UPDATE_USR_ID, UPDATE_DT)
VALUES ('DEP0000004', 'Asset Lab', 'Asset Lab', '솔루션 개발팀 산하 Assetlab', 'DEP0000003', 1, 'STS0000001', 'superadmin', systimestamp, 'superadmin',  systimestamp);

INSERT INTO TB_FR_DEPT_INFO (DEPT_SQ, DEPT_ID, DEPT_NM, DESCRIPTION, PARENT_DEPT, DEPT_PRIOITY, STATUS_CD, CREATE_USR_ID, CREATE_DT, UPDATE_USR_ID, UPDATE_DT)
VALUES ('DEP0000005', 'DevPlatformLab', 'Dev. Platform Lab', '솔루션 개발팀 산하 Dev. Platform Lab', 'DEP0000003', 1, 'STS0000001', 'superadmin', systimestamp, 'superadmin',  systimestamp);

