INSERT INTO TB_FR_MENU_AUTH_MAP
(WORKGROUP_SQ, MENU_SQ, READ_YN, UPDATE_YN, EXECUTE_YN ,CREATE_DT ,CREATE_USR_ID ,UPDATE_DT ,UPDATE_USR_ID )
VALUES ('ADM_000001', 'ADM_000001', 1, 1, 1, systimestamp, 'superadmin', systimestamp, 'superadmin');

INSERT INTO TB_FR_MENU_AUTH_MAP
(WORKGROUP_SQ, MENU_SQ, READ_YN, UPDATE_YN, EXECUTE_YN ,CREATE_DT ,CREATE_USR_ID ,UPDATE_DT ,UPDATE_USR_ID )
VALUES ('ADM_000001', 'ADM_000002', 1, 1, 1, systimestamp, 'superadmin', systimestamp, 'superadmin');

INSERT INTO TB_FR_MENU_AUTH_MAP
(WORKGROUP_SQ, MENU_SQ, READ_YN, UPDATE_YN, EXECUTE_YN ,CREATE_DT ,CREATE_USR_ID ,UPDATE_DT ,UPDATE_USR_ID )
VALUES ('ADM_000001', 'ADM_000003', 1, 1, 1, systimestamp, 'superadmin', systimestamp, 'superadmin');

INSERT INTO TB_FR_MENU_AUTH_MAP
(WORKGROUP_SQ, MENU_SQ, READ_YN, UPDATE_YN, EXECUTE_YN ,CREATE_DT ,CREATE_USR_ID ,UPDATE_DT ,UPDATE_USR_ID )
VALUES ('ADM_000001', 'ADM_000004', 1, 1, 1, systimestamp, 'superadmin', systimestamp, 'superadmin');

INSERT INTO TB_FR_MENU_AUTH_MAP
(WORKGROUP_SQ, MENU_SQ, READ_YN, UPDATE_YN, EXECUTE_YN ,CREATE_DT ,CREATE_USR_ID ,UPDATE_DT ,UPDATE_USR_ID )
VALUES ('ADM_000001', 'ADM_000005', 1, 1, 1, systimestamp, 'superadmin', systimestamp, 'superadmin');

INSERT INTO TB_FR_MENU_AUTH_MAP
(WORKGROUP_SQ, MENU_SQ, READ_YN, UPDATE_YN, EXECUTE_YN ,CREATE_DT ,CREATE_USR_ID ,UPDATE_DT ,UPDATE_USR_ID )
VALUES ('ADM_000001', 'ADM_000006', 1, 1, 1, systimestamp, 'superadmin', systimestamp, 'superadmin');

INSERT INTO TB_FR_MENU_AUTH_MAP
(WORKGROUP_SQ, MENU_SQ, READ_YN, UPDATE_YN, EXECUTE_YN ,CREATE_DT ,CREATE_USR_ID ,UPDATE_DT ,UPDATE_USR_ID )
VALUES ('ADM_000001', 'ADM_000007', 1, 1, 1, systimestamp, 'superadmin', systimestamp, 'superadmin');

INSERT INTO TB_FR_MENU_AUTH_MAP
(WORKGROUP_SQ, MENU_SQ, READ_YN, UPDATE_YN, EXECUTE_YN ,CREATE_DT ,CREATE_USR_ID ,UPDATE_DT ,UPDATE_USR_ID )
VALUES ('ADM_000001', 'ADM_000008', 1, 1, 1, systimestamp, 'superadmin', systimestamp, 'superadmin');

INSERT INTO TB_FR_MENU_AUTH_MAP
(WORKGROUP_SQ, MENU_SQ, READ_YN, UPDATE_YN, EXECUTE_YN ,CREATE_DT ,CREATE_USR_ID ,UPDATE_DT ,UPDATE_USR_ID )
VALUES ('ADM_000001', 'ADM_000009', 1, 1, 1, systimestamp, 'superadmin', systimestamp, 'superadmin');

INSERT INTO TB_FR_MENU_AUTH_MAP
(WORKGROUP_SQ, MENU_SQ, READ_YN, UPDATE_YN, EXECUTE_YN ,CREATE_DT ,CREATE_USR_ID ,UPDATE_DT ,UPDATE_USR_ID )
VALUES ('ADM_000001', 'ADM_000010', 1, 1, 1, systimestamp, 'superadmin', systimestamp, 'superadmin');

INSERT INTO TB_FR_MENU_AUTH_MAP
(WORKGROUP_SQ, MENU_SQ, READ_YN, UPDATE_YN, EXECUTE_YN ,CREATE_DT ,CREATE_USR_ID ,UPDATE_DT ,UPDATE_USR_ID )
VALUES ('ADM_000001', 'ADM_000011', 1, 1, 1, systimestamp, 'superadmin', systimestamp, 'superadmin');

INSERT INTO TB_FR_MENU_AUTH_MAP
(WORKGROUP_SQ, MENU_SQ, READ_YN, UPDATE_YN, EXECUTE_YN ,CREATE_DT ,CREATE_USR_ID ,UPDATE_DT ,UPDATE_USR_ID )
VALUES ('ADM_000001', 'ADM_000012', 1, 1, 1, systimestamp, 'superadmin', systimestamp, 'superadmin');

INSERT INTO TB_FR_MENU_AUTH_MAP
(WORKGROUP_SQ, MENU_SQ, READ_YN, UPDATE_YN, EXECUTE_YN ,CREATE_DT ,CREATE_USR_ID ,UPDATE_DT ,UPDATE_USR_ID )
VALUES ('ADM_000001', 'ADM_000013', 1, 1, 1, systimestamp, 'superadmin', systimestamp, 'superadmin');

INSERT INTO TB_FR_MENU_AUTH_MAP
(WORKGROUP_SQ, MENU_SQ, READ_YN, UPDATE_YN, EXECUTE_YN ,CREATE_DT ,CREATE_USR_ID ,UPDATE_DT ,UPDATE_USR_ID )
VALUES ('ADM_000001', 'ADM_000015', 1, 1, 1, systimestamp, 'superadmin', systimestamp, 'superadmin');

INSERT INTO TB_FR_MENU_AUTH_MAP
(WORKGROUP_SQ, MENU_SQ, READ_YN, UPDATE_YN, EXECUTE_YN ,CREATE_DT ,CREATE_USR_ID ,UPDATE_DT ,UPDATE_USR_ID )
VALUES ('ADM_000001', 'ADM_000016', 1, 1, 1, systimestamp, 'superadmin', systimestamp, 'superadmin');

INSERT INTO TB_FR_MENU_AUTH_MAP
(WORKGROUP_SQ, MENU_SQ, READ_YN, UPDATE_YN, EXECUTE_YN ,CREATE_DT ,CREATE_USR_ID ,UPDATE_DT ,UPDATE_USR_ID )
VALUES ('ADM_000001', 'ADM_000017', 1, 1, 1, systimestamp, 'superadmin', systimestamp, 'superadmin');

INSERT INTO TB_FR_MENU_AUTH_MAP
(WORKGROUP_SQ, MENU_SQ, READ_YN, UPDATE_YN, EXECUTE_YN ,CREATE_DT ,CREATE_USR_ID ,UPDATE_DT ,UPDATE_USR_ID )
VALUES ('ADM_000001', 'ADM_000018', 1, 1, 1, systimestamp, 'superadmin', systimestamp, 'superadmin');

INSERT INTO TB_FR_MENU_AUTH_MAP
(WORKGROUP_SQ, MENU_SQ, READ_YN, UPDATE_YN, EXECUTE_YN ,CREATE_DT ,CREATE_USR_ID ,UPDATE_DT ,UPDATE_USR_ID )
VALUES ('ADM_000002', 'ADM_000001', 1, 0, 0, systimestamp, 'superadmin', systimestamp, 'superadmin');

INSERT INTO TB_FR_MENU_AUTH_MAP
(WORKGROUP_SQ, MENU_SQ, READ_YN, UPDATE_YN, EXECUTE_YN ,CREATE_DT ,CREATE_USR_ID ,UPDATE_DT ,UPDATE_USR_ID )
VALUES ('ADM_000002', 'ADM_000002', 1, 0, 0, systimestamp, 'superadmin', systimestamp, 'superadmin');

INSERT INTO TB_FR_MENU_AUTH_MAP
(WORKGROUP_SQ, MENU_SQ, READ_YN, UPDATE_YN, EXECUTE_YN ,CREATE_DT ,CREATE_USR_ID ,UPDATE_DT ,UPDATE_USR_ID )
VALUES ('ADM_000002', 'ADM_000003', 1, 0, 0, systimestamp, 'superadmin', systimestamp, 'superadmin');

INSERT INTO TB_FR_MENU_AUTH_MAP
(WORKGROUP_SQ, MENU_SQ, READ_YN, UPDATE_YN, EXECUTE_YN ,CREATE_DT ,CREATE_USR_ID ,UPDATE_DT ,UPDATE_USR_ID )
VALUES ('ADM_000002', 'ADM_000004', 1, 0, 0, systimestamp, 'superadmin', systimestamp, 'superadmin');

INSERT INTO TB_FR_MENU_AUTH_MAP
(WORKGROUP_SQ, MENU_SQ, READ_YN, UPDATE_YN, EXECUTE_YN ,CREATE_DT ,CREATE_USR_ID ,UPDATE_DT ,UPDATE_USR_ID )
VALUES ('ADM_000002', 'ADM_000005', 1, 0, 0, systimestamp, 'superadmin', systimestamp, 'superadmin');

INSERT INTO TB_FR_MENU_AUTH_MAP
(WORKGROUP_SQ, MENU_SQ, READ_YN, UPDATE_YN, EXECUTE_YN ,CREATE_DT ,CREATE_USR_ID ,UPDATE_DT ,UPDATE_USR_ID )
VALUES ('ADM_000002', 'ADM_000006', 1, 0, 0, systimestamp, 'superadmin', systimestamp, 'superadmin');

INSERT INTO TB_FR_MENU_AUTH_MAP
(WORKGROUP_SQ, MENU_SQ, READ_YN, UPDATE_YN, EXECUTE_YN ,CREATE_DT ,CREATE_USR_ID ,UPDATE_DT ,UPDATE_USR_ID )
VALUES ('ADM_000002', 'ADM_000007', 1, 0, 0, systimestamp, 'superadmin', systimestamp, 'superadmin');

INSERT INTO TB_FR_MENU_AUTH_MAP
(WORKGROUP_SQ, MENU_SQ, READ_YN, UPDATE_YN, EXECUTE_YN ,CREATE_DT ,CREATE_USR_ID ,UPDATE_DT ,UPDATE_USR_ID )
VALUES ('ADM_000002', 'ADM_000008', 1, 0, 0, systimestamp, 'superadmin', systimestamp, 'superadmin');

INSERT INTO TB_FR_MENU_AUTH_MAP
(WORKGROUP_SQ, MENU_SQ, READ_YN, UPDATE_YN, EXECUTE_YN ,CREATE_DT ,CREATE_USR_ID ,UPDATE_DT ,UPDATE_USR_ID )
VALUES ('ADM_000002', 'ADM_000009', 1, 0, 0, systimestamp, 'superadmin', systimestamp, 'superadmin');

INSERT INTO TB_FR_MENU_AUTH_MAP
(WORKGROUP_SQ, MENU_SQ, READ_YN, UPDATE_YN, EXECUTE_YN ,CREATE_DT ,CREATE_USR_ID ,UPDATE_DT ,UPDATE_USR_ID )
VALUES ('ADM_000002', 'ADM_000010', 1, 0, 0, systimestamp, 'superadmin', systimestamp, 'superadmin');

INSERT INTO TB_FR_MENU_AUTH_MAP
(WORKGROUP_SQ, MENU_SQ, READ_YN, UPDATE_YN, EXECUTE_YN ,CREATE_DT ,CREATE_USR_ID ,UPDATE_DT ,UPDATE_USR_ID )
VALUES ('ADM_000002', 'ADM_000011', 1, 0, 0, systimestamp, 'superadmin', systimestamp, 'superadmin');

INSERT INTO TB_FR_MENU_AUTH_MAP
(WORKGROUP_SQ, MENU_SQ, READ_YN, UPDATE_YN, EXECUTE_YN ,CREATE_DT ,CREATE_USR_ID ,UPDATE_DT ,UPDATE_USR_ID )
VALUES ('ADM_000002', 'ADM_000012', 1, 0, 0, systimestamp, 'superadmin', systimestamp, 'superadmin');

INSERT INTO TB_FR_MENU_AUTH_MAP
(WORKGROUP_SQ, MENU_SQ, READ_YN, UPDATE_YN, EXECUTE_YN ,CREATE_DT ,CREATE_USR_ID ,UPDATE_DT ,UPDATE_USR_ID )
VALUES ('ADM_000002', 'ADM_000013', 1, 0, 0, systimestamp, 'superadmin', systimestamp, 'superadmin');

INSERT INTO TB_FR_MENU_AUTH_MAP
(WORKGROUP_SQ, MENU_SQ, READ_YN, UPDATE_YN, EXECUTE_YN ,CREATE_DT ,CREATE_USR_ID ,UPDATE_DT ,UPDATE_USR_ID )
VALUES ('ADM_000002', 'ADM_000015', 1, 0, 0, systimestamp, 'superadmin', systimestamp, 'superadmin');

INSERT INTO TB_FR_MENU_AUTH_MAP
(WORKGROUP_SQ, MENU_SQ, READ_YN, UPDATE_YN, EXECUTE_YN ,CREATE_DT ,CREATE_USR_ID ,UPDATE_DT ,UPDATE_USR_ID )
VALUES ('ADM_000002', 'ADM_000016', 1, 0, 0, systimestamp, 'superadmin', systimestamp, 'superadmin');

INSERT INTO TB_FR_MENU_AUTH_MAP
(WORKGROUP_SQ, MENU_SQ, READ_YN, UPDATE_YN, EXECUTE_YN ,CREATE_DT ,CREATE_USR_ID ,UPDATE_DT ,UPDATE_USR_ID )
VALUES ('ADM_000002', 'ADM_000017', 1, 0, 0, systimestamp, 'superadmin', systimestamp, 'superadmin');

INSERT INTO TB_FR_MENU_AUTH_MAP
(WORKGROUP_SQ, MENU_SQ, READ_YN, UPDATE_YN, EXECUTE_YN ,CREATE_DT ,CREATE_USR_ID ,UPDATE_DT ,UPDATE_USR_ID )
VALUES ('ADM_000002', 'ADM_000018', 1, 0, 0, systimestamp, 'superadmin', systimestamp, 'superadmin');
