INSERT INTO TB_FR_CODE_MULTI_LANG_INFO
( CODE_SQ, COUNTRY_CD, MESSAGE_VALUE,  CREATE_DT, CREATE_USR_ID )
VALUES ('CDT_000001','EN', 'CODE',   systimestamp,'superadmin' );

INSERT INTO TB_FR_CODE_MULTI_LANG_INFO
( CODE_SQ, COUNTRY_CD, MESSAGE_VALUE,  CREATE_DT, CREATE_USR_ID )
VALUES ('CDT_000012','EN','LEVEL_CODE',  systimestamp,'superadmin' );

INSERT INTO TB_FR_CODE_MULTI_LANG_INFO
( CODE_SQ, COUNTRY_CD, MESSAGE_VALUE,  CREATE_DT, CREATE_USR_ID )
VALUES ('GRD_000000', 'EN','L0',  systimestamp,'superadmin' );

INSERT INTO TB_FR_CODE_MULTI_LANG_INFO
( CODE_SQ, COUNTRY_CD, MESSAGE_VALUE,  CREATE_DT, CREATE_USR_ID )
VALUES ('GRD_000001','EN','L1(Assistant Engineer)',  systimestamp,'superadmin' );

INSERT INTO TB_FR_CODE_MULTI_LANG_INFO
( CODE_SQ, COUNTRY_CD, MESSAGE_VALUE,  CREATE_DT, CREATE_USR_ID )
VALUES ('GRD_000002','EN','L2(Assistant Engineer)',   systimestamp,'superadmin' );

INSERT INTO TB_FR_CODE_MULTI_LANG_INFO
( CODE_SQ, COUNTRY_CD, MESSAGE_VALUE,  CREATE_DT, CREATE_USR_ID )
VALUES ('GRD_000003','EN','L3(Senior Engineer)',  systimestamp,'superadmin' );

INSERT INTO TB_FR_CODE_MULTI_LANG_INFO
( CODE_SQ, COUNTRY_CD, MESSAGE_VALUE,  CREATE_DT, CREATE_USR_ID )
VALUES ('GRD_000004','EN','L4(Senior Engineer)',  systimestamp,'superadmin' );

INSERT INTO TB_FR_CODE_MULTI_LANG_INFO
( CODE_SQ, COUNTRY_CD, MESSAGE_VALUE,  CREATE_DT, CREATE_USR_ID )
VALUES ('GRD_000005','EN','L5(Principal Engineer)',  systimestamp,'superadmin' );

INSERT INTO TB_FR_CODE_MULTI_LANG_INFO
( CODE_SQ, COUNTRY_CD, MESSAGE_VALUE,  CREATE_DT, CREATE_USR_ID )
VALUES ('CDT_000013','EN','STATUS_CODE',    systimestamp,'superadmin' );

INSERT INTO TB_FR_CODE_MULTI_LANG_INFO
( CODE_SQ, COUNTRY_CD, MESSAGE_VALUE,  CREATE_DT, CREATE_USR_ID )
VALUES ('USR_000001','EN','LOGIN_TYPE',   systimestamp,'superadmin' );

INSERT INTO TB_FR_CODE_MULTI_LANG_INFO
( CODE_SQ, COUNTRY_CD, MESSAGE_VALUE,  CREATE_DT, CREATE_USR_ID )
VALUES ('LOG_000001','EN', 'LOG_CODE',   systimestamp,'superadmin' );



INSERT INTO TB_FR_CODE_MULTI_LANG_INFO
( CODE_SQ, COUNTRY_CD, MESSAGE_VALUE,  CREATE_DT, CREATE_USR_ID )
VALUES ('STS_010000','EN','USER_STATUS',   systimestamp,'superadmin' );

INSERT INTO TB_FR_CODE_MULTI_LANG_INFO
( CODE_SQ, COUNTRY_CD, MESSAGE_VALUE,  CREATE_DT, CREATE_USR_ID )
VALUES ('STS_010100','EN','On usable',  systimestamp,'superadmin' );

INSERT INTO TB_FR_CODE_MULTI_LANG_INFO
( CODE_SQ, COUNTRY_CD, MESSAGE_VALUE,  CREATE_DT, CREATE_USR_ID )
VALUES ('STS_010200','EN','On waiting',  systimestamp,'superadmin' );

INSERT INTO TB_FR_CODE_MULTI_LANG_INFO
( CODE_SQ, COUNTRY_CD, MESSAGE_VALUE,  CREATE_DT, CREATE_USR_ID )
VALUES ('CDT_000014','EN','MESSAGE_CODE',  systimestamp,'superadmin' );

INSERT INTO TB_FR_CODE_MULTI_LANG_INFO
( CODE_SQ, COUNTRY_CD, MESSAGE_VALUE,  CREATE_DT, CREATE_USR_ID )
VALUES ('MSG_010000','EN','MESSAGE_LARGE_CATEGORY',    systimestamp,'superadmin' );

INSERT INTO TB_FR_CODE_MULTI_LANG_INFO
( CODE_SQ, COUNTRY_CD, MESSAGE_VALUE,  CREATE_DT, CREATE_USR_ID )
VALUES ('MSG_010001','EN','UI', systimestamp,'superadmin' );

INSERT INTO TB_FR_CODE_MULTI_LANG_INFO
( CODE_SQ, COUNTRY_CD, MESSAGE_VALUE,  CREATE_DT, CREATE_USR_ID )
VALUES ('MSG_010002','EN','COM',    systimestamp,'superadmin' );

INSERT INTO TB_FR_CODE_MULTI_LANG_INFO
( CODE_SQ, COUNTRY_CD, MESSAGE_VALUE,  CREATE_DT, CREATE_USR_ID )
VALUES ('MSG_010003','EN','SERV',    systimestamp,'superadmin' );

INSERT INTO TB_FR_CODE_MULTI_LANG_INFO
( CODE_SQ, COUNTRY_CD, MESSAGE_VALUE,  CREATE_DT, CREATE_USR_ID )
VALUES ('MSG_020000','EN','MESSAGE_MEDIUM_CATEGORY',   systimestamp,'superadmin' );

INSERT INTO TB_FR_CODE_MULTI_LANG_INFO
( CODE_SQ, COUNTRY_CD, MESSAGE_VALUE,  CREATE_DT, CREATE_USR_ID )
VALUES ('MSG_020001','EN','MSG',  systimestamp,'superadmin' );

INSERT INTO TB_FR_CODE_MULTI_LANG_INFO
( CODE_SQ, COUNTRY_CD, MESSAGE_VALUE,  CREATE_DT, CREATE_USR_ID )
VALUES ('MSG_020002','EN','TEXT',  systimestamp,'superadmin' );

INSERT INTO TB_FR_CODE_MULTI_LANG_INFO
( CODE_SQ, COUNTRY_CD, MESSAGE_VALUE,  CREATE_DT, CREATE_USR_ID )
VALUES ('MSG_030000','EN','MESSAGE_SMALL_CATEGORY',  systimestamp,'superadmin' );

INSERT INTO TB_FR_CODE_MULTI_LANG_INFO
( CODE_SQ, COUNTRY_CD, MESSAGE_VALUE,  CREATE_DT, CREATE_USR_ID )
VALUES ('MSG_030001','EN','ERR',   systimestamp,'superadmin' );

INSERT INTO TB_FR_CODE_MULTI_LANG_INFO
( CODE_SQ, COUNTRY_CD, MESSAGE_VALUE,  CREATE_DT, CREATE_USR_ID )
VALUES ('MSG_030002','EN','WARN',   systimestamp,'superadmin' );

INSERT INTO TB_FR_CODE_MULTI_LANG_INFO
( CODE_SQ, COUNTRY_CD, MESSAGE_VALUE,  CREATE_DT, CREATE_USR_ID )
VALUES ('MSG_030003','EN','LABEL',    systimestamp,'superadmin' );

INSERT INTO TB_FR_CODE_MULTI_LANG_INFO
( CODE_SQ, COUNTRY_CD, MESSAGE_VALUE,  CREATE_DT, CREATE_USR_ID )
VALUES ('MSG_030004','EN','CON', systimestamp,'superadmin' );

INSERT INTO TB_FR_CODE_MULTI_LANG_INFO
( CODE_SQ, COUNTRY_CD, MESSAGE_VALUE,  CREATE_DT, CREATE_USR_ID )
VALUES ('MSG_030005','EN','SUCC', systimestamp,'superadmin' );

INSERT INTO TB_FR_CODE_MULTI_LANG_INFO
( CODE_SQ, COUNTRY_CD, MESSAGE_VALUE,  CREATE_DT, CREATE_USR_ID )
VALUES ('MSG_030006','EN','BTN',  systimestamp,'superadmin' );

INSERT INTO TB_FR_CODE_MULTI_LANG_INFO
( CODE_SQ, COUNTRY_CD, MESSAGE_VALUE,  CREATE_DT, CREATE_USR_ID )
VALUES ('MSG_030007','EN','FORM',  systimestamp,'superadmin' );

INSERT INTO TB_FR_CODE_MULTI_LANG_INFO
( CODE_SQ, COUNTRY_CD, MESSAGE_VALUE,  CREATE_DT, CREATE_USR_ID )
VALUES ('USR_000011','EN','ID LOGIN',  systimestamp,'superadmin' );

INSERT INTO TB_FR_CODE_MULTI_LANG_INFO
( CODE_SQ, COUNTRY_CD, MESSAGE_VALUE,  CREATE_DT, CREATE_USR_ID )
VALUES ('USR_000012','EN','SSO LOGIN',  systimestamp,'superadmin' );

INSERT INTO TB_FR_CODE_MULTI_LANG_INFO
( CODE_SQ, COUNTRY_CD, MESSAGE_VALUE,  CREATE_DT, CREATE_USR_ID )
VALUES ('STS_010300','EN','On unregistered',  systimestamp,'superadmin' );

INSERT INTO TB_FR_CODE_MULTI_LANG_INFO
( CODE_SQ, COUNTRY_CD, MESSAGE_VALUE,  CREATE_DT, CREATE_USR_ID )
VALUES ('STS_010400','EN','On locked',  systimestamp,'superadmin' );

INSERT INTO TB_FR_CODE_MULTI_LANG_INFO
( CODE_SQ, COUNTRY_CD, MESSAGE_VALUE,  CREATE_DT, CREATE_USR_ID )
VALUES ('LOG_000011','EN','LOGIN_CODE',  systimestamp,'superadmin' );

INSERT INTO TB_FR_CODE_MULTI_LANG_INFO
( CODE_SQ, COUNTRY_CD, MESSAGE_VALUE,  CREATE_DT, CREATE_USR_ID )
VALUES ('LOG_000012','EN','LOGOUT_CODE',  systimestamp,'superadmin' );

INSERT INTO TB_FR_CODE_MULTI_LANG_INFO
( CODE_SQ, COUNTRY_CD, MESSAGE_VALUE,  CREATE_DT, CREATE_USR_ID )
VALUES ('LOG_000013','EN','LOGIN_FAILED_CODE',   systimestamp,'superadmin' );

