INSERT INTO TB_FR_CODE_INFO
( CODE_SQ, CODE_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CODE_ORDER_NO, CREATE_DT, CREATE_USR_ID, USE_YN, INIT_YN)
VALUES ('CDT_000001','CODE', '0',  'Main CODE' , '0',  '1',  SYSTIMESTAMP,'superadmin', 'Y' , 'Y' );

INSERT INTO TB_FR_CODE_INFO
( CODE_SQ, CODE_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CODE_ORDER_NO, CREATE_DT, CREATE_USR_ID, USE_YN, INIT_YN)
VALUES ('CDT_000012','LEVEL_CODE', 'CDT_000001',  'level code' , '1',  '1',  SYSTIMESTAMP,'superadmin', 'Y' , 'Y' );

INSERT INTO TB_FR_CODE_INFO
( CODE_SQ, CODE_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CODE_ORDER_NO, CREATE_DT, CREATE_USR_ID, USE_YN, INIT_YN)
VALUES ('GRD_000000','L0', 'CDT_000012',  '임시 혹은 알 수 없음' , '1',  '1',  SYSTIMESTAMP,'superadmin', 'Y' , 'Y' );

INSERT INTO TB_FR_CODE_INFO
( CODE_SQ, CODE_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CODE_ORDER_NO, CREATE_DT, CREATE_USR_ID, USE_YN, INIT_YN)
VALUES ('GRD_000001','L1(Assistant Engineer)', 'CDT_000012',  '사원' , '1',  '2',  SYSTIMESTAMP,'superadmin', 'Y' , 'Y' );

INSERT INTO TB_FR_CODE_INFO
( CODE_SQ, CODE_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CODE_ORDER_NO, CREATE_DT, CREATE_USR_ID, USE_YN, INIT_YN)
VALUES ('GRD_000002','L2(Assistant Engineer)', 'CDT_000012',  '선임' , '1',  '3',  SYSTIMESTAMP,'superadmin', 'Y' , 'Y' );

INSERT INTO TB_FR_CODE_INFO
( CODE_SQ, CODE_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CODE_ORDER_NO, CREATE_DT, CREATE_USR_ID, USE_YN, INIT_YN)
VALUES ('GRD_000003','L3(Senior Engineer)', 'CDT_000012',  '책임' , '1',  '4',  SYSTIMESTAMP,'superadmin', 'Y' , 'Y' );


INSERT INTO TB_FR_CODE_INFO
( CODE_SQ, CODE_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CODE_ORDER_NO, CREATE_DT, CREATE_USR_ID, USE_YN, INIT_YN)
VALUES ('GRD_000004','L4(Senior Engineer)', 'CDT_000012',  '수석보' , '1',  '4',  SYSTIMESTAMP,'superadmin', 'Y', 'Y');

INSERT INTO TB_FR_CODE_INFO
( CODE_SQ, CODE_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CODE_ORDER_NO, CREATE_DT, CREATE_USR_ID, USE_YN, INIT_YN)
VALUES ('GRD_000005','L5(Principal Engineer)', 'CDT_000012',  '수석' , '1',  '4',  SYSTIMESTAMP,'superadmin', 'Y', 'Y');
INSERT INTO TB_FR_CODE_INFO
( CODE_SQ, CODE_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CODE_ORDER_NO, CREATE_DT, CREATE_USR_ID, USE_YN, INIT_YN)
VALUES ('CDT_000013','STATUS_CODE', 'CDT_000001',  'status code' , '1',  '2',  SYSTIMESTAMP,'superadmin', 'Y' , 'Y' );

INSERT INTO TB_FR_CODE_INFO
( CODE_SQ, CODE_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CODE_ORDER_NO, CREATE_DT, CREATE_USR_ID, USE_YN, INIT_YN)
VALUES ('USR_000001','LOGIN_TYPE', 'CDT_000001',  'login type' , '1',  '3',  SYSTIMESTAMP,'superadmin', 'Y' , 'Y' );

INSERT INTO TB_FR_CODE_INFO
( CODE_SQ, CODE_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CODE_ORDER_NO, CREATE_DT, CREATE_USR_ID, USE_YN, INIT_YN)
VALUES ('LOG_000001','LOG_CODE', 'CDT_000001',  'log code' , '1',  '4',  SYSTIMESTAMP,'superadmin', 'Y' , 'Y' );

INSERT INTO TB_FR_CODE_INFO
( CODE_SQ, CODE_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CODE_ORDER_NO, CREATE_DT, CREATE_USR_ID, USE_YN, INIT_YN)
VALUES ('STS_010000','USER_STATUS', 'CDT_000013',  'User status code' , '2',  '1',  SYSTIMESTAMP,'superadmin', 'Y' , 'Y' );

INSERT INTO TB_FR_CODE_INFO
( CODE_SQ, CODE_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CODE_ORDER_NO, CREATE_DT, CREATE_USR_ID, USE_YN, INIT_YN)
VALUES ('STS_010100','사용중', 'STS_010000',  '사용중' , '3',  '1',  SYSTIMESTAMP,'superadmin', 'Y' , 'Y' );

INSERT INTO TB_FR_CODE_INFO
( CODE_SQ, CODE_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CODE_ORDER_NO, CREATE_DT, CREATE_USR_ID, USE_YN, INIT_YN)
VALUES ('STS_010200','대기중', 'STS_010000',  '승인대기 상태' , '3',  '2',  SYSTIMESTAMP,'superadmin', 'Y' , 'Y' );

INSERT INTO TB_FR_CODE_INFO
( CODE_SQ, CODE_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CODE_ORDER_NO, CREATE_DT, CREATE_USR_ID, USE_YN, INIT_YN)
VALUES ('CDT_000014','MESSAGE_CODE', 'CDT_000001',  'massage code' , '1',  '5',  SYSTIMESTAMP,'superadmin', 'Y' , 'Y' );

INSERT INTO TB_FR_CODE_INFO
( CODE_SQ, CODE_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CODE_ORDER_NO, CREATE_DT, CREATE_USR_ID, USE_YN, INIT_YN)
VALUES ('MSG_010000','MESSAGE_LARGE_CATEGORY', 'CDT_000014',  'large category in message' , '2',  '1',  SYSTIMESTAMP,'superadmin', 'Y' , 'Y' );

INSERT INTO TB_FR_CODE_INFO
( CODE_SQ, CODE_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CODE_ORDER_NO, CREATE_DT, CREATE_USR_ID, USE_YN, INIT_YN)
VALUES ('MSG_010001','UI', 'MSG_010000',  'UI' , '3',  '1',  SYSTIMESTAMP,'superadmin', 'Y' , 'Y' );

INSERT INTO TB_FR_CODE_INFO
( CODE_SQ, CODE_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CODE_ORDER_NO, CREATE_DT, CREATE_USR_ID, USE_YN, INIT_YN)
VALUES ('MSG_010002','COM', 'MSG_010000',  'COM' , '3',  '2',  SYSTIMESTAMP,'superadmin', 'Y' , 'Y' );

INSERT INTO TB_FR_CODE_INFO
( CODE_SQ, CODE_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CODE_ORDER_NO, CREATE_DT, CREATE_USR_ID, USE_YN, INIT_YN)
VALUES ('MSG_010003','SERV', 'MSG_010000',  'SERV' , '3',  '3',  SYSTIMESTAMP,'superadmin', 'Y' , 'Y' );

INSERT INTO TB_FR_CODE_INFO
( CODE_SQ, CODE_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CODE_ORDER_NO, CREATE_DT, CREATE_USR_ID, USE_YN, INIT_YN)
VALUES ('MSG_020000','MESSAGE_MEDIUM_CATEGORY', 'CDT_000014',  'medium category in message' , '2',  '2',  SYSTIMESTAMP,'superadmin', 'Y' , 'Y' );

INSERT INTO TB_FR_CODE_INFO
( CODE_SQ, CODE_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CODE_ORDER_NO, CREATE_DT, CREATE_USR_ID, USE_YN, INIT_YN)
VALUES ('MSG_020001','MSG', 'MSG_020000',  'MSG' , '3',  '1',  SYSTIMESTAMP,'superadmin', 'Y' , 'Y' );

INSERT INTO TB_FR_CODE_INFO
( CODE_SQ, CODE_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CODE_ORDER_NO, CREATE_DT, CREATE_USR_ID, USE_YN, INIT_YN)
VALUES ('MSG_020002','TEXT', 'MSG_020000',  'TEXT' , '3',  '2',  SYSTIMESTAMP,'superadmin', 'Y' , 'Y' );

INSERT INTO TB_FR_CODE_INFO
( CODE_SQ, CODE_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CODE_ORDER_NO, CREATE_DT, CREATE_USR_ID, USE_YN, INIT_YN)
VALUES ('MSG_030000','MESSAGE_SMALL_CATEGORY', 'CDT_000014',  'small category in message' , '2',  '3',  SYSTIMESTAMP,'superadmin', 'Y' , 'Y' );

INSERT INTO TB_FR_CODE_INFO
( CODE_SQ, CODE_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CODE_ORDER_NO, CREATE_DT, CREATE_USR_ID, USE_YN, INIT_YN)
VALUES ('MSG_030001','ERR', 'MSG_030000',  'ERROR' , '3',  '1',  SYSTIMESTAMP,'superadmin', 'Y' , 'Y' );

INSERT INTO TB_FR_CODE_INFO
( CODE_SQ, CODE_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CODE_ORDER_NO, CREATE_DT, CREATE_USR_ID, USE_YN, INIT_YN)
VALUES ('MSG_030002','WARN', 'MSG_030000',  'WARN' , '3',  '2',  SYSTIMESTAMP,'superadmin', 'Y' , 'Y' );

INSERT INTO TB_FR_CODE_INFO
( CODE_SQ, CODE_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CODE_ORDER_NO, CREATE_DT, CREATE_USR_ID, USE_YN, INIT_YN)
VALUES ('MSG_030003','LABEL', 'MSG_030000',  'LABEL' , '3',  '3',  SYSTIMESTAMP,'superadmin', 'Y' , 'Y' );

INSERT INTO TB_FR_CODE_INFO
( CODE_SQ, CODE_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CODE_ORDER_NO, CREATE_DT, CREATE_USR_ID, USE_YN, INIT_YN)
VALUES ('MSG_030004','CON', 'MSG_030000',  'CON' , '3',  '4',  SYSTIMESTAMP,'superadmin', 'Y' , 'Y' );

INSERT INTO TB_FR_CODE_INFO
( CODE_SQ, CODE_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CODE_ORDER_NO, CREATE_DT, CREATE_USR_ID, USE_YN, INIT_YN)
VALUES ('MSG_030005','SUCC', 'MSG_030000',  'SUCC' , '3',  '5',  SYSTIMESTAMP,'superadmin', 'Y' , 'Y' );

INSERT INTO TB_FR_CODE_INFO
( CODE_SQ, CODE_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CODE_ORDER_NO, CREATE_DT, CREATE_USR_ID, USE_YN, INIT_YN)
VALUES ('MSG_030006','BTN', 'MSG_030000',  'BTN' , '3',  '6',  SYSTIMESTAMP,'superadmin', 'Y' , 'Y' );

INSERT INTO TB_FR_CODE_INFO
( CODE_SQ, CODE_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CODE_ORDER_NO, CREATE_DT, CREATE_USR_ID, USE_YN, INIT_YN)
VALUES ('MSG_030007','FORM', 'MSG_030000',  'FORM' , '3',  '7',  SYSTIMESTAMP,'superadmin', 'Y' , 'Y' );

INSERT INTO TB_FR_CODE_INFO
( CODE_SQ, CODE_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CODE_ORDER_NO, CREATE_DT, CREATE_USR_ID, USE_YN, INIT_YN)
VALUES ('USR_000011','ID LOGIN', 'USR_000001',  'ID LOGIN' , '1',  '1',  SYSTIMESTAMP,'superadmin', 'Y' , 'Y' );

INSERT INTO TB_FR_CODE_INFO
( CODE_SQ, CODE_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CODE_ORDER_NO, CREATE_DT, CREATE_USR_ID, USE_YN, INIT_YN)
VALUES ('USR_000012','SSO LOGIN', 'USR_000001',  'SSO LOGIN' , '1',  '2',  SYSTIMESTAMP,'superadmin', 'Y' , 'Y' );

INSERT INTO TB_FR_CODE_INFO
( CODE_SQ, CODE_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CODE_ORDER_NO, CREATE_DT, CREATE_USR_ID, USE_YN, INIT_YN)
VALUES ('STS_010300','탈퇴', 'STS_010000',  '탈퇴 상태' , '3',  '3',  SYSTIMESTAMP,'superadmin', 'Y' , 'Y' );

INSERT INTO TB_FR_CODE_INFO
( CODE_SQ, CODE_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CODE_ORDER_NO, CREATE_DT, CREATE_USR_ID, USE_YN, INIT_YN)
VALUES ('STS_010400','잠김', 'STS_010000',  '비밀번호 오류로 잠김' , '3',  '4',  SYSTIMESTAMP,'superadmin', 'Y' , 'Y' );

INSERT INTO TB_FR_CODE_INFO
( CODE_SQ, CODE_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CODE_ORDER_NO, CREATE_DT, CREATE_USR_ID, USE_YN, INIT_YN)
VALUES ('LOG_000011','LOGIN_CODE', 'LOG_000001',  'Login' , '2',  '1',  SYSTIMESTAMP,'superadmin', 'Y' , 'Y' );

INSERT INTO TB_FR_CODE_INFO
( CODE_SQ, CODE_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CODE_ORDER_NO, CREATE_DT, CREATE_USR_ID, USE_YN, INIT_YN)
VALUES ('LOG_000012','LOGOUT_CODE', 'LOG_000001',  'Logout' , '2',  '2',  SYSTIMESTAMP,'superadmin', 'Y' , 'Y' );

INSERT INTO TB_FR_CODE_INFO
( CODE_SQ, CODE_NM, PARENT_CODE_SQ, CODE_DESCRIPTION, CODE_LEVEL_NO, CODE_ORDER_NO, CREATE_DT, CREATE_USR_ID, USE_YN, INIT_YN)
VALUES ('LOG_000013','LOGIN_FAILED_CODE', 'LOG_000001',  'Login Failed' , '2',  '3',  SYSTIMESTAMP,'superadmin', 'Y' , 'Y' );

