CREATE TABLE IF NOT EXISTS TB_FR_CODE_INFO (
  CODE_SQ varchar(10) PRIMARY KEY NOT NULL,
  CODE_NM varchar(50) NOT NULL,
  PARENT_CODE_SQ varchar(10) NOT NULL,
  CODE_DESCRIPTION VARCHAR(2000),
  CODE_LEVEL_NO INT NOT NULL,
  CREATE_DT TIMESTAMP DEFAULT NULL,
  CREATE_USR_ID VARCHAR(20) DEFAULT NULL,
  UPDATE_DT TIMESTAMP DEFAULT NULL,
  UPDATE_USR_ID VARCHAR(20) DEFAULT NULL,
  USE_YN VARCHAR(1) NOT NULL,
  INIT_YN VARCHAR(1),
  CODE_ORDER_NO INT DEFAULT '0'
);