CREATE TABLE IF NOT EXISTS TB_FR_CODE_MULTI_LANG_INFO (
  CODE_SQ varchar(10)  NOT NULL,
  COUNTRY_CD VARCHAR(2) NOT NULL ,
  MESSAGE_VALUE VARCHAR(50) NOT NULL ,
  CREATE_USR_ID VARCHAR(20) DEFAULT NULL,
  CREATE_DT TIMESTAMP DEFAULT NULL,
  UPDATE_USR_ID VARCHAR(20) DEFAULT NULL,
  UPDATE_DT TIMESTAMP DEFAULT NULL,
     PRIMARY KEY (CODE_SQ, COUNTRY_CD),
    FOREIGN KEY (CODE_SQ) REFERENCES TB_FR_CODE_INFO (CODE_SQ),
    FOREIGN KEY (COUNTRY_CD)   REFERENCES TB_FR_LANGUAGE_INFO (LANGUAGE_ID)
);
