DROP TABLE TB_FR_DEPT_INFO IF EXISTS;
CREATE TABLE IF NOT EXISTS TB_FR_DEPT_INFO (
  DEPT_SQ VARCHAR(10) NOT NULL,
  DEPT_ID VARCHAR(20) NOT NULL,
  DEPT_NM VARCHAR(50) NOT NULL,
  DESCRIPTION VARCHAR(500) NOT NULL,
  PARENT_DEPT VARCHAR(10) NOT NULL,
  DEPT_PRIOITY INT(4) NULL,
  STATUS_CD VARCHAR(10) NULL DEFAULT 'Y',
  CREATE_USR_ID VARCHAR(45) NULL DEFAULT NULL,
  CREATE_DT DATETIME NULL DEFAULT NULL,
  UPDATE_USR_ID VARCHAR(45) NULL DEFAULT NULL,
  UPDATE_DT DATETIME NULL,
  
  PRIMARY KEY (DEPT_SQ)
 );
