DROP TABLE TB_FR_LANGUAGE_INFO IF EXISTS;
CREATE TABLE IF NOT EXISTS TB_FR_LANGUAGE_INFO (
  	LANGUAGE_SQ varchar(10) NOT NULL,
  	LANGUAGE_ID varchar(2) NOT NULL,
  	LANGUAGE_NM VARCHAR(100),
  	USE_YN VARCHAR(1) NOT NULL,
  	ORDER_NO INT DEFAULT '0',
	CREATE_DT TIMESTAMP DEFAULT NULL,
	CREATE_USR_ID VARCHAR(20) DEFAULT NULL,
	PRIMARY KEY (LANGUAGE_SQ),
  	UNIQUE KEY (LANGUAGE_ID)
);