DROP TABLE TB_FR_MOVIE_INFO IF EXISTS;
CREATE TABLE IF NOT EXISTS TB_FR_MOVIE_INFO (
  MOVIE_SQ varchar(10) PRIMARY KEY NOT NULL,
  MOVIE_NM varchar(50) NOT NULL,
  GENRE_CD varchar(10) NOT NULL,
  ACTORS varchar(100) NOT NULL,
  DESCRIPTION VARCHAR(2000),
  CREATE_DT TIMESTAMP DEFAULT NULL,
  CREATE_USR_ID VARCHAR(20) DEFAULT NULL,
  UPDATE_DT TIMESTAMP DEFAULT NULL,
  UPDATE_USR_ID VARCHAR(20) DEFAULT NULL,
  FOREIGN KEY (GENRE_CD) REFERENCES TB_FR_CODE_INFO(CODE_SQ)
);