DROP TABLE TB_FR_SYS_LOG IF EXISTS;
CREATE TABLE IF NOT EXISTS TB_FR_SYS_LOG (
  LOG_SQ VARCHAR(20)   PRIMARY KEY  NOT NULL,
  EVENT_IP VARCHAR(45) NOT NULL,
  USER_ID VARCHAR(20) NOT NULL,
  EVENT_DT TIMESTAMP NOT NULL,
  EVENT_CD VARCHAR(10) NOT NULL,
  LOG_MSG CLOB DEFAULT NULL,
);