DROP TABLE TB_HC_COMM_CD_INFO IF EXISTS;
CREATE TABLE IF NOT EXISTS TB_HC_CODE_INFO (
  CODE_SQ VARCHAR(10) PRIMARY KEY NOT NULL,
  CODE_NM VARCHAR(50) NOT NULL,
  CODE_ENG_NM VARCHAR(50) NOT NULL,
  PARENT_CODE_SQ VARCHAR(10) NOT NULL,
  CODE_DESCRIPTION VARCHAR(2000),
  CODE_LEVEL_NO INT,
  CREATE_DT TIMESTAMP DEFAULT NULL,
  CREATE_USR_ID VARCHAR(20) DEFAULT NULL,
  UPDATE_DT TIMESTAMP DEFAULT NULL,
  UPDATE_USR_ID VARCHAR(20) DEFAULT NULL,
  USE_YN VARCHAR(1) NOT NULL,
  CODE_ORDER_NO INT DEFAULT '0'
);