DROP TABLE TB_HC_HOLIDAY_INFO IF EXISTS;
CREATE TABLE IF NOT EXISTS TB_HC_HOLIDAY_INFO (
  HOLIDAY_SQ VARCHAR(8) PRIMARY KEY NOT NULL,
  COUNTRY_CD VARCHAR(2) NOT NULL,
  HOLIDAY_NM VARCHAR(100) NOT NULL,
  HOLIDAY_ST_DT VARCHAR(8) NOT NULL,
  HOLIDAY_END_DT VARCHAR(8) NOT NULL,
  HOLIDAY_YN VARCHAR(1) NOT NULL,
  HOLIDAY_DESCRIPTION VARCHAR(2000),
  CREATE_DT TIMESTAMP DEFAULT NULL,
  USE_YN VARCHAR(1) NOT NULL,
  CREATE_USR_ID VARCHAR(20) DEFAULT NULL,
  UPDATE_DT TIMESTAMP DEFAULT NULL,
  UPDATE_USR_ID VARCHAR(20) DEFAULT NULL
);