INSERT INTO TB_FR_MENU_MULTI_LANG_INFO
( MENU_SQ, COUNTRY_CD, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('ADM_000001', 'EN', 'MENU',  'superadmin', GETDATE() );

INSERT INTO TB_FR_MENU_MULTI_LANG_INFO
( MENU_SQ, COUNTRY_CD, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('ADM_000002','EN','Systems management',   'superadmin', GETDATE() );

INSERT INTO TB_FR_MENU_MULTI_LANG_INFO
( MENU_SQ, COUNTRY_CD, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('ADM_000003','EN','User management',   'superadmin', GETDATE() );

INSERT INTO TB_FR_MENU_MULTI_LANG_INFO
( MENU_SQ, COUNTRY_CD, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('ADM_000004','EN','Menu/Role  management',  'superadmin', GETDATE() );

INSERT INTO TB_FR_MENU_MULTI_LANG_INFO
( MENU_SQ, COUNTRY_CD, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('ADM_000005','EN','Menu management',   'superadmin', GETDATE() );

INSERT INTO TB_FR_MENU_MULTI_LANG_INFO
( MENU_SQ, COUNTRY_CD, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('ADM_000006','EN','Role management',  'superadmin', GETDATE() );

INSERT INTO TB_FR_MENU_MULTI_LANG_INFO
( MENU_SQ, COUNTRY_CD, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('ADM_000007','EN','Workgroup management',  'superadmin', GETDATE() );

INSERT INTO TB_FR_MENU_MULTI_LANG_INFO
( MENU_SQ, COUNTRY_CD, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('ADM_000008','EN','Log management ',  'superadmin', GETDATE() );

INSERT INTO TB_FR_MENU_MULTI_LANG_INFO
( MENU_SQ, COUNTRY_CD, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('ADM_000009', 'EN','Login history  management',  'superadmin', GETDATE() );

INSERT INTO TB_FR_MENU_MULTI_LANG_INFO
( MENU_SQ, COUNTRY_CD, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('ADM_000010', 'EN','Other management',  'superadmin', GETDATE() );

INSERT INTO TB_FR_MENU_MULTI_LANG_INFO
( MENU_SQ, COUNTRY_CD, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('ADM_000011','EN','Code management',  'superadmin', GETDATE() );

INSERT INTO TB_FR_MENU_MULTI_LANG_INFO
( MENU_SQ, COUNTRY_CD, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('ADM_000012', 'EN','Workgroup history  mgnt',  'superadmin', GETDATE() );

INSERT INTO TB_FR_MENU_MULTI_LANG_INFO
( MENU_SQ, COUNTRY_CD, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('ADM_000013','EN','User management',   'superadmin', GETDATE() );

INSERT INTO TB_FR_MENU_MULTI_LANG_INFO
( MENU_SQ, COUNTRY_CD, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('ADM_000015','EN','User Change',   'superadmin', GETDATE() );

INSERT INTO TB_FR_MENU_MULTI_LANG_INFO
( MENU_SQ, COUNTRY_CD, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('ADM_000016','EN','Message management', 'superadmin', GETDATE() );

INSERT INTO TB_FR_MENU_MULTI_LANG_INFO
( MENU_SQ, COUNTRY_CD, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('ADM_000017','EN','Samples', 'superadmin', GETDATE() );

INSERT INTO TB_FR_MENU_MULTI_LANG_INFO
( MENU_SQ, COUNTRY_CD, MESSAGE_VALUE, CREATE_USR_ID, CREATE_DT)
VALUES ('ADM_000018', 'EN','ESB Mail Sender',  'superadmin', GETDATE() );
