INSERT INTO TB_FR_WORKGROUP_INFO
(WORKGROUP_SQ, WORKGROUP_ID, WORKGROUP_NM, DESCRIPTION, USE_YN, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID)
VALUES ('ADM_000001', 'ADMIN_WORKGROUP', '관리자그룹', '관리자 계정을 위한 업무그룹', 'Y', GETDATE(), 'superadmin', GETDATE(), 'superadmin');
INSERT INTO TB_FR_WORKGROUP_INFO
(WORKGROUP_SQ, WORKGROUP_ID, WORKGROUP_NM, DESCRIPTION, USE_YN, CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID)
VALUES ('ADM_000002', 'TEST_WORKGROUP', '테스트그룹', 'TEST 계정을 위한 업무그룹', 'Y', GETDATE(), 'superadmin', GETDATE(), 'superadmin');
