INSERT INTO TB_FR_WORKGROUP_ROLE_MAP
(WORKGROUP_SQ, ROLE_SQ,  CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID)
VALUES ('ADM_000001', 'ADM_000002',  GETDATE(), 'superadmin', GETDATE(), 'superadmin');

INSERT INTO TB_FR_WORKGROUP_ROLE_MAP
(WORKGROUP_SQ, ROLE_SQ,  CREATE_DT, CREATE_USR_ID, UPDATE_DT, UPDATE_USR_ID)
VALUES ('ADM_000002', 'ADM_000003',  GETDATE(), 'superadmin', GETDATE(), 'superadmin');



